// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/transport/http/client"
)

// Injectors from wire.go:

func Init(opts *Options) (*Client, error) {
	manager := newManager()
	client := newClient(opts, manager)
	return client, nil
}

// wire.go:

type (
	Options struct {
		Telemetry *telemetry.Telemetry
	}
)

func newManager() client.Manager {
	return client.New()
}

func newClient(
	opts *Options,
	manager client.Manager,
) *Client {
	return &Client{
		Telemetry: opts.Telemetry,
		Manager:   manager,
	}
}
