// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// CreateStaticAccessToken provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CreateStaticAccessToken(ctx context.Context, data CreateStaticAccessTokenData) (string, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateStaticAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateStaticAccessTokenData) (string, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateStaticAccessTokenData) string); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateStaticAccessTokenData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_CreateStaticAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStaticAccessToken'
type MockAdapter_CreateStaticAccessToken_Call struct {
	*mock.Call
}

// CreateStaticAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - data CreateStaticAccessTokenData
func (_e *MockAdapter_Expecter) CreateStaticAccessToken(ctx interface{}, data interface{}) *MockAdapter_CreateStaticAccessToken_Call {
	return &MockAdapter_CreateStaticAccessToken_Call{Call: _e.mock.On("CreateStaticAccessToken", ctx, data)}
}

func (_c *MockAdapter_CreateStaticAccessToken_Call) Run(run func(ctx context.Context, data CreateStaticAccessTokenData)) *MockAdapter_CreateStaticAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateStaticAccessTokenData
		if args[1] != nil {
			arg1 = args[1].(CreateStaticAccessTokenData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_CreateStaticAccessToken_Call) Return(s string, err error) *MockAdapter_CreateStaticAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAdapter_CreateStaticAccessToken_Call) RunAndReturn(run func(ctx context.Context, data CreateStaticAccessTokenData) (string, error)) *MockAdapter_CreateStaticAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptAuthRequest provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DecryptAuthRequest(ctx context.Context, data []byte) ([]byte, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for DecryptAuthRequest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_DecryptAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptAuthRequest'
type MockAdapter_DecryptAuthRequest_Call struct {
	*mock.Call
}

// DecryptAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockAdapter_Expecter) DecryptAuthRequest(ctx interface{}, data interface{}) *MockAdapter_DecryptAuthRequest_Call {
	return &MockAdapter_DecryptAuthRequest_Call{Call: _e.mock.On("DecryptAuthRequest", ctx, data)}
}

func (_c *MockAdapter_DecryptAuthRequest_Call) Run(run func(ctx context.Context, data []byte)) *MockAdapter_DecryptAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_DecryptAuthRequest_Call) Return(bytes []byte, err error) *MockAdapter_DecryptAuthRequest_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAdapter_DecryptAuthRequest_Call) RunAndReturn(run func(ctx context.Context, data []byte) ([]byte, error)) *MockAdapter_DecryptAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DeleteSession(ctx context.Context, user uint, device string) error {
	ret := _mock.Called(ctx, user, device)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = returnFunc(ctx, user, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockAdapter_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user uint
//   - device string
func (_e *MockAdapter_Expecter) DeleteSession(ctx interface{}, user interface{}, device interface{}) *MockAdapter_DeleteSession_Call {
	return &MockAdapter_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, user, device)}
}

func (_c *MockAdapter_DeleteSession_Call) Run(run func(ctx context.Context, user uint, device string)) *MockAdapter_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_DeleteSession_Call) Return(err error) *MockAdapter_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, user uint, device string) error) *MockAdapter_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStaticAccessToken provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DeleteStaticAccessToken(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStaticAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_DeleteStaticAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStaticAccessToken'
type MockAdapter_DeleteStaticAccessToken_Call struct {
	*mock.Call
}

// DeleteStaticAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdapter_Expecter) DeleteStaticAccessToken(ctx interface{}, id interface{}) *MockAdapter_DeleteStaticAccessToken_Call {
	return &MockAdapter_DeleteStaticAccessToken_Call{Call: _e.mock.On("DeleteStaticAccessToken", ctx, id)}
}

func (_c *MockAdapter_DeleteStaticAccessToken_Call) Run(run func(ctx context.Context, id string)) *MockAdapter_DeleteStaticAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_DeleteStaticAccessToken_Call) Return(err error) *MockAdapter_DeleteStaticAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_DeleteStaticAccessToken_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAdapter_DeleteStaticAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptAuthResponse provides a mock function for the type MockAdapter
func (_mock *MockAdapter) EncryptAuthResponse(ctx context.Context, data []byte) ([]byte, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for EncryptAuthResponse")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_EncryptAuthResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptAuthResponse'
type MockAdapter_EncryptAuthResponse_Call struct {
	*mock.Call
}

// EncryptAuthResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockAdapter_Expecter) EncryptAuthResponse(ctx interface{}, data interface{}) *MockAdapter_EncryptAuthResponse_Call {
	return &MockAdapter_EncryptAuthResponse_Call{Call: _e.mock.On("EncryptAuthResponse", ctx, data)}
}

func (_c *MockAdapter_EncryptAuthResponse_Call) Run(run func(ctx context.Context, data []byte)) *MockAdapter_EncryptAuthResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_EncryptAuthResponse_Call) Return(bytes []byte, err error) *MockAdapter_EncryptAuthResponse_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAdapter_EncryptAuthResponse_Call) RunAndReturn(run func(ctx context.Context, data []byte) ([]byte, error)) *MockAdapter_EncryptAuthResponse_Call {
	_c.Call.Return(run)
	return _c
}

// FilterStaticAccessTokens provides a mock function for the type MockAdapter
func (_mock *MockAdapter) FilterStaticAccessTokens(ctx context.Context, data FilterStaticAccessTokenData) ([]StaticAccessTokenResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for FilterStaticAccessTokens")
	}

	var r0 []StaticAccessTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterStaticAccessTokenData) ([]StaticAccessTokenResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterStaticAccessTokenData) []StaticAccessTokenResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]StaticAccessTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FilterStaticAccessTokenData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_FilterStaticAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterStaticAccessTokens'
type MockAdapter_FilterStaticAccessTokens_Call struct {
	*mock.Call
}

// FilterStaticAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - data FilterStaticAccessTokenData
func (_e *MockAdapter_Expecter) FilterStaticAccessTokens(ctx interface{}, data interface{}) *MockAdapter_FilterStaticAccessTokens_Call {
	return &MockAdapter_FilterStaticAccessTokens_Call{Call: _e.mock.On("FilterStaticAccessTokens", ctx, data)}
}

func (_c *MockAdapter_FilterStaticAccessTokens_Call) Run(run func(ctx context.Context, data FilterStaticAccessTokenData)) *MockAdapter_FilterStaticAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FilterStaticAccessTokenData
		if args[1] != nil {
			arg1 = args[1].(FilterStaticAccessTokenData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_FilterStaticAccessTokens_Call) Return(staticAccessTokenResults []StaticAccessTokenResult, err error) *MockAdapter_FilterStaticAccessTokens_Call {
	_c.Call.Return(staticAccessTokenResults, err)
	return _c
}

func (_c *MockAdapter_FilterStaticAccessTokens_Call) RunAndReturn(run func(ctx context.Context, data FilterStaticAccessTokenData) ([]StaticAccessTokenResult, error)) *MockAdapter_FilterStaticAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveDevices provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetActiveDevices(ctx context.Context, user uint) ([]Device, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveDevices")
	}

	var r0 []Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]Device, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []Device); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetActiveDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveDevices'
type MockAdapter_GetActiveDevices_Call struct {
	*mock.Call
}

// GetActiveDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - user uint
func (_e *MockAdapter_Expecter) GetActiveDevices(ctx interface{}, user interface{}) *MockAdapter_GetActiveDevices_Call {
	return &MockAdapter_GetActiveDevices_Call{Call: _e.mock.On("GetActiveDevices", ctx, user)}
}

func (_c *MockAdapter_GetActiveDevices_Call) Run(run func(ctx context.Context, user uint)) *MockAdapter_GetActiveDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_GetActiveDevices_Call) Return(devices []Device, err error) *MockAdapter_GetActiveDevices_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *MockAdapter_GetActiveDevices_Call) RunAndReturn(run func(ctx context.Context, user uint) ([]Device, error)) *MockAdapter_GetActiveDevices_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetSession(ctx context.Context, user uint, device string) (*Session, error) {
	ret := _mock.Called(ctx, user, device)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (*Session, error)); ok {
		return returnFunc(ctx, user, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) *Session); ok {
		r0 = returnFunc(ctx, user, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, user, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockAdapter_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user uint
//   - device string
func (_e *MockAdapter_Expecter) GetSession(ctx interface{}, user interface{}, device interface{}) *MockAdapter_GetSession_Call {
	return &MockAdapter_GetSession_Call{Call: _e.mock.On("GetSession", ctx, user, device)}
}

func (_c *MockAdapter_GetSession_Call) Run(run func(ctx context.Context, user uint, device string)) *MockAdapter_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_GetSession_Call) Return(session *Session, err error) *MockAdapter_GetSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockAdapter_GetSession_Call) RunAndReturn(run func(ctx context.Context, user uint, device string) (*Session, error)) *MockAdapter_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewSession provides a mock function for the type MockAdapter
func (_mock *MockAdapter) NewSession(ctx context.Context, user uint, device string, session *Session) error {
	ret := _mock.Called(ctx, user, device, session)

	if len(ret) == 0 {
		panic("no return value specified for NewSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, *Session) error); ok {
		r0 = returnFunc(ctx, user, device, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_NewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSession'
type MockAdapter_NewSession_Call struct {
	*mock.Call
}

// NewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user uint
//   - device string
//   - session *Session
func (_e *MockAdapter_Expecter) NewSession(ctx interface{}, user interface{}, device interface{}, session interface{}) *MockAdapter_NewSession_Call {
	return &MockAdapter_NewSession_Call{Call: _e.mock.On("NewSession", ctx, user, device, session)}
}

func (_c *MockAdapter_NewSession_Call) Run(run func(ctx context.Context, user uint, device string, session *Session)) *MockAdapter_NewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *Session
		if args[3] != nil {
			arg3 = args[3].(*Session)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapter_NewSession_Call) Return(err error) *MockAdapter_NewSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_NewSession_Call) RunAndReturn(run func(ctx context.Context, user uint, device string, session *Session) error) *MockAdapter_NewSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokens provides a mock function for the type MockAdapter
func (_mock *MockAdapter) NewTokens(ctx context.Context, data NewTokenData) (*NewTokensResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NewTokens")
	}

	var r0 *NewTokensResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewTokenData) (*NewTokensResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewTokenData) *NewTokensResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NewTokensResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NewTokenData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_NewTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTokens'
type MockAdapter_NewTokens_Call struct {
	*mock.Call
}

// NewTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - data NewTokenData
func (_e *MockAdapter_Expecter) NewTokens(ctx interface{}, data interface{}) *MockAdapter_NewTokens_Call {
	return &MockAdapter_NewTokens_Call{Call: _e.mock.On("NewTokens", ctx, data)}
}

func (_c *MockAdapter_NewTokens_Call) Run(run func(ctx context.Context, data NewTokenData)) *MockAdapter_NewTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NewTokenData
		if args[1] != nil {
			arg1 = args[1].(NewTokenData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_NewTokens_Call) Return(newTokensResult *NewTokensResult, err error) *MockAdapter_NewTokens_Call {
	_c.Call.Return(newTokensResult, err)
	return _c
}

func (_c *MockAdapter_NewTokens_Call) RunAndReturn(run func(ctx context.Context, data NewTokenData) (*NewTokensResult, error)) *MockAdapter_NewTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccessToken provides a mock function for the type MockAdapter
func (_mock *MockAdapter) ParseAccessToken(ctx context.Context, token string) (*ParseTokenResult, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 *ParseTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ParseTokenResult, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ParseTokenResult); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ParseTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type MockAdapter_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAdapter_Expecter) ParseAccessToken(ctx interface{}, token interface{}) *MockAdapter_ParseAccessToken_Call {
	return &MockAdapter_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", ctx, token)}
}

func (_c *MockAdapter_ParseAccessToken_Call) Run(run func(ctx context.Context, token string)) *MockAdapter_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_ParseAccessToken_Call) Return(parseTokenResult *ParseTokenResult, err error) *MockAdapter_ParseAccessToken_Call {
	_c.Call.Return(parseTokenResult, err)
	return _c
}

func (_c *MockAdapter_ParseAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*ParseTokenResult, error)) *MockAdapter_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function for the type MockAdapter
func (_mock *MockAdapter) ParseRefreshToken(ctx context.Context, token string) (*ParseTokenResult, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *ParseTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ParseTokenResult, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ParseTokenResult); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ParseTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockAdapter_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAdapter_Expecter) ParseRefreshToken(ctx interface{}, token interface{}) *MockAdapter_ParseRefreshToken_Call {
	return &MockAdapter_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", ctx, token)}
}

func (_c *MockAdapter_ParseRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockAdapter_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_ParseRefreshToken_Call) Return(parseTokenResult *ParseTokenResult, err error) *MockAdapter_ParseRefreshToken_Call {
	_c.Call.Return(parseTokenResult, err)
	return _c
}

func (_c *MockAdapter_ParseRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*ParseTokenResult, error)) *MockAdapter_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function for the type MockAdapter
func (_mock *MockAdapter) UpdateSession(ctx context.Context, user uint, device string, jti string) error {
	ret := _mock.Called(ctx, user, device, jti)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = returnFunc(ctx, user, device, jti)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type MockAdapter_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user uint
//   - device string
//   - jti string
func (_e *MockAdapter_Expecter) UpdateSession(ctx interface{}, user interface{}, device interface{}, jti interface{}) *MockAdapter_UpdateSession_Call {
	return &MockAdapter_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, user, device, jti)}
}

func (_c *MockAdapter_UpdateSession_Call) Run(run func(ctx context.Context, user uint, device string, jti string)) *MockAdapter_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapter_UpdateSession_Call) Return(err error) *MockAdapter_UpdateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_UpdateSession_Call) RunAndReturn(run func(ctx context.Context, user uint, device string, jti string) error) *MockAdapter_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}
