// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tokens

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function for the type MockService
func (_mock *MockService) Auth(ctx context.Context, data *AuthData) (*AuthResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 *AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AuthData) (*AuthResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AuthData) *AuthResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *AuthData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockService_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
//   - ctx context.Context
//   - data *AuthData
func (_e *MockService_Expecter) Auth(ctx interface{}, data interface{}) *MockService_Auth_Call {
	return &MockService_Auth_Call{Call: _e.mock.On("Auth", ctx, data)}
}

func (_c *MockService_Auth_Call) Run(run func(ctx context.Context, data *AuthData)) *MockService_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AuthData
		if args[1] != nil {
			arg1 = args[1].(*AuthData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Auth_Call) Return(authResult *AuthResult, err error) *MockService_Auth_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *MockService_Auth_Call) RunAndReturn(run func(ctx context.Context, data *AuthData) (*AuthResult, error)) *MockService_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Auth2fa provides a mock function for the type MockService
func (_mock *MockService) Auth2fa(ctx context.Context, data Auth2faData) (*Auth2faResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Auth2fa")
	}

	var r0 *Auth2faResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Auth2faData) (*Auth2faResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Auth2faData) *Auth2faResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Auth2faResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Auth2faData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Auth2fa_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth2fa'
type MockService_Auth2fa_Call struct {
	*mock.Call
}

// Auth2fa is a helper method to define mock.On call
//   - ctx context.Context
//   - data Auth2faData
func (_e *MockService_Expecter) Auth2fa(ctx interface{}, data interface{}) *MockService_Auth2fa_Call {
	return &MockService_Auth2fa_Call{Call: _e.mock.On("Auth2fa", ctx, data)}
}

func (_c *MockService_Auth2fa_Call) Run(run func(ctx context.Context, data Auth2faData)) *MockService_Auth2fa_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Auth2faData
		if args[1] != nil {
			arg1 = args[1].(Auth2faData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Auth2fa_Call) Return(auth2faResult *Auth2faResult, err error) *MockService_Auth2fa_Call {
	_c.Call.Return(auth2faResult, err)
	return _c
}

func (_c *MockService_Auth2fa_Call) RunAndReturn(run func(ctx context.Context, data Auth2faData) (*Auth2faResult, error)) *MockService_Auth2fa_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStaticAccessToken provides a mock function for the type MockService
func (_mock *MockService) CreateStaticAccessToken(ctx context.Context, data CreateStaticAccessTokenData) (string, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateStaticAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateStaticAccessTokenData) (string, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateStaticAccessTokenData) string); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateStaticAccessTokenData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateStaticAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStaticAccessToken'
type MockService_CreateStaticAccessToken_Call struct {
	*mock.Call
}

// CreateStaticAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - data CreateStaticAccessTokenData
func (_e *MockService_Expecter) CreateStaticAccessToken(ctx interface{}, data interface{}) *MockService_CreateStaticAccessToken_Call {
	return &MockService_CreateStaticAccessToken_Call{Call: _e.mock.On("CreateStaticAccessToken", ctx, data)}
}

func (_c *MockService_CreateStaticAccessToken_Call) Run(run func(ctx context.Context, data CreateStaticAccessTokenData)) *MockService_CreateStaticAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateStaticAccessTokenData
		if args[1] != nil {
			arg1 = args[1].(CreateStaticAccessTokenData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateStaticAccessToken_Call) Return(s string, err error) *MockService_CreateStaticAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_CreateStaticAccessToken_Call) RunAndReturn(run func(ctx context.Context, data CreateStaticAccessTokenData) (string, error)) *MockService_CreateStaticAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptAuthRequest provides a mock function for the type MockService
func (_mock *MockService) DecryptAuthRequest(ctx context.Context, data []byte, target any) error {
	ret := _mock.Called(ctx, data, target)

	if len(ret) == 0 {
		panic("no return value specified for DecryptAuthRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, any) error); ok {
		r0 = returnFunc(ctx, data, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DecryptAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptAuthRequest'
type MockService_DecryptAuthRequest_Call struct {
	*mock.Call
}

// DecryptAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - target any
func (_e *MockService_Expecter) DecryptAuthRequest(ctx interface{}, data interface{}, target interface{}) *MockService_DecryptAuthRequest_Call {
	return &MockService_DecryptAuthRequest_Call{Call: _e.mock.On("DecryptAuthRequest", ctx, data, target)}
}

func (_c *MockService_DecryptAuthRequest_Call) Run(run func(ctx context.Context, data []byte, target any)) *MockService_DecryptAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DecryptAuthRequest_Call) Return(err error) *MockService_DecryptAuthRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DecryptAuthRequest_Call) RunAndReturn(run func(ctx context.Context, data []byte, target any) error) *MockService_DecryptAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStaticAccessToken provides a mock function for the type MockService
func (_mock *MockService) DeleteStaticAccessToken(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStaticAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteStaticAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStaticAccessToken'
type MockService_DeleteStaticAccessToken_Call struct {
	*mock.Call
}

// DeleteStaticAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteStaticAccessToken(ctx interface{}, id interface{}) *MockService_DeleteStaticAccessToken_Call {
	return &MockService_DeleteStaticAccessToken_Call{Call: _e.mock.On("DeleteStaticAccessToken", ctx, id)}
}

func (_c *MockService_DeleteStaticAccessToken_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteStaticAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteStaticAccessToken_Call) Return(err error) *MockService_DeleteStaticAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteStaticAccessToken_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_DeleteStaticAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptAuthResponse provides a mock function for the type MockService
func (_mock *MockService) EncryptAuthResponse(ctx context.Context, data []byte) ([]byte, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for EncryptAuthResponse")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_EncryptAuthResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptAuthResponse'
type MockService_EncryptAuthResponse_Call struct {
	*mock.Call
}

// EncryptAuthResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockService_Expecter) EncryptAuthResponse(ctx interface{}, data interface{}) *MockService_EncryptAuthResponse_Call {
	return &MockService_EncryptAuthResponse_Call{Call: _e.mock.On("EncryptAuthResponse", ctx, data)}
}

func (_c *MockService_EncryptAuthResponse_Call) Run(run func(ctx context.Context, data []byte)) *MockService_EncryptAuthResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_EncryptAuthResponse_Call) Return(bytes []byte, err error) *MockService_EncryptAuthResponse_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockService_EncryptAuthResponse_Call) RunAndReturn(run func(ctx context.Context, data []byte) ([]byte, error)) *MockService_EncryptAuthResponse_Call {
	_c.Call.Return(run)
	return _c
}

// FilterStaticAccessTokens provides a mock function for the type MockService
func (_mock *MockService) FilterStaticAccessTokens(ctx context.Context, data FilterStaticAccessTokenData) ([]StaticAccessTokenResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for FilterStaticAccessTokens")
	}

	var r0 []StaticAccessTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterStaticAccessTokenData) ([]StaticAccessTokenResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterStaticAccessTokenData) []StaticAccessTokenResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]StaticAccessTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FilterStaticAccessTokenData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FilterStaticAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterStaticAccessTokens'
type MockService_FilterStaticAccessTokens_Call struct {
	*mock.Call
}

// FilterStaticAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - data FilterStaticAccessTokenData
func (_e *MockService_Expecter) FilterStaticAccessTokens(ctx interface{}, data interface{}) *MockService_FilterStaticAccessTokens_Call {
	return &MockService_FilterStaticAccessTokens_Call{Call: _e.mock.On("FilterStaticAccessTokens", ctx, data)}
}

func (_c *MockService_FilterStaticAccessTokens_Call) Run(run func(ctx context.Context, data FilterStaticAccessTokenData)) *MockService_FilterStaticAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FilterStaticAccessTokenData
		if args[1] != nil {
			arg1 = args[1].(FilterStaticAccessTokenData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FilterStaticAccessTokens_Call) Return(staticAccessTokenResults []StaticAccessTokenResult, err error) *MockService_FilterStaticAccessTokens_Call {
	_c.Call.Return(staticAccessTokenResults, err)
	return _c
}

func (_c *MockService_FilterStaticAccessTokens_Call) RunAndReturn(run func(ctx context.Context, data FilterStaticAccessTokenData) ([]StaticAccessTokenResult, error)) *MockService_FilterStaticAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// TokenRenew provides a mock function for the type MockService
func (_mock *MockService) TokenRenew(ctx context.Context, data TokenRenewData) (*TokenRenewResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for TokenRenew")
	}

	var r0 *TokenRenewResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TokenRenewData) (*TokenRenewResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TokenRenewData) *TokenRenewResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TokenRenewResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TokenRenewData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_TokenRenew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenRenew'
type MockService_TokenRenew_Call struct {
	*mock.Call
}

// TokenRenew is a helper method to define mock.On call
//   - ctx context.Context
//   - data TokenRenewData
func (_e *MockService_Expecter) TokenRenew(ctx interface{}, data interface{}) *MockService_TokenRenew_Call {
	return &MockService_TokenRenew_Call{Call: _e.mock.On("TokenRenew", ctx, data)}
}

func (_c *MockService_TokenRenew_Call) Run(run func(ctx context.Context, data TokenRenewData)) *MockService_TokenRenew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TokenRenewData
		if args[1] != nil {
			arg1 = args[1].(TokenRenewData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_TokenRenew_Call) Return(tokenRenewResult *TokenRenewResult, err error) *MockService_TokenRenew_Call {
	_c.Call.Return(tokenRenewResult, err)
	return _c
}

func (_c *MockService_TokenRenew_Call) RunAndReturn(run func(ctx context.Context, data TokenRenewData) (*TokenRenewResult, error)) *MockService_TokenRenew_Call {
	_c.Call.Return(run)
	return _c
}

// TokenValidate provides a mock function for the type MockService
func (_mock *MockService) TokenValidate(ctx context.Context, data TokenValidateData) (*TokenValidateResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for TokenValidate")
	}

	var r0 *TokenValidateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TokenValidateData) (*TokenValidateResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TokenValidateData) *TokenValidateResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TokenValidateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TokenValidateData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_TokenValidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenValidate'
type MockService_TokenValidate_Call struct {
	*mock.Call
}

// TokenValidate is a helper method to define mock.On call
//   - ctx context.Context
//   - data TokenValidateData
func (_e *MockService_Expecter) TokenValidate(ctx interface{}, data interface{}) *MockService_TokenValidate_Call {
	return &MockService_TokenValidate_Call{Call: _e.mock.On("TokenValidate", ctx, data)}
}

func (_c *MockService_TokenValidate_Call) Run(run func(ctx context.Context, data TokenValidateData)) *MockService_TokenValidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TokenValidateData
		if args[1] != nil {
			arg1 = args[1].(TokenValidateData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_TokenValidate_Call) Return(tokenValidateResult *TokenValidateResult, err error) *MockService_TokenValidate_Call {
	_c.Call.Return(tokenValidateResult, err)
	return _c
}

func (_c *MockService_TokenValidate_Call) RunAndReturn(run func(ctx context.Context, data TokenValidateData) (*TokenValidateResult, error)) *MockService_TokenValidate_Call {
	_c.Call.Return(run)
	return _c
}
