// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/transport/http/server"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Auth(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockAdapter_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) Auth(ctx interface{}, reqCtx interface{}) *MockAdapter_Auth_Call {
	return &MockAdapter_Auth_Call{Call: _e.mock.On("Auth", ctx, reqCtx)}
}

func (_c *MockAdapter_Auth_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_Auth_Call) Return() *MockAdapter_Auth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_Auth_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_Auth_Call {
	_c.Run(run)
	return _c
}

// Auth2fa provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Auth2fa(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_Auth2fa_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth2fa'
type MockAdapter_Auth2fa_Call struct {
	*mock.Call
}

// Auth2fa is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) Auth2fa(ctx interface{}, reqCtx interface{}) *MockAdapter_Auth2fa_Call {
	return &MockAdapter_Auth2fa_Call{Call: _e.mock.On("Auth2fa", ctx, reqCtx)}
}

func (_c *MockAdapter_Auth2fa_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_Auth2fa_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_Auth2fa_Call) Return() *MockAdapter_Auth2fa_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_Auth2fa_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_Auth2fa_Call {
	_c.Run(run)
	return _c
}

// CreateStaticAccessToken provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CreateStaticAccessToken(ctx context.Context, reqCtx *server.RequestContext, req *CreateStaticAccessTokenRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_CreateStaticAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStaticAccessToken'
type MockAdapter_CreateStaticAccessToken_Call struct {
	*mock.Call
}

// CreateStaticAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *CreateStaticAccessTokenRequest
func (_e *MockAdapter_Expecter) CreateStaticAccessToken(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_CreateStaticAccessToken_Call {
	return &MockAdapter_CreateStaticAccessToken_Call{Call: _e.mock.On("CreateStaticAccessToken", ctx, reqCtx, req)}
}

func (_c *MockAdapter_CreateStaticAccessToken_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *CreateStaticAccessTokenRequest)) *MockAdapter_CreateStaticAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *CreateStaticAccessTokenRequest
		if args[2] != nil {
			arg2 = args[2].(*CreateStaticAccessTokenRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_CreateStaticAccessToken_Call) Return() *MockAdapter_CreateStaticAccessToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_CreateStaticAccessToken_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *CreateStaticAccessTokenRequest)) *MockAdapter_CreateStaticAccessToken_Call {
	_c.Run(run)
	return _c
}

// DeleteStaticAccessToken provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DeleteStaticAccessToken(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_DeleteStaticAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStaticAccessToken'
type MockAdapter_DeleteStaticAccessToken_Call struct {
	*mock.Call
}

// DeleteStaticAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) DeleteStaticAccessToken(ctx interface{}, reqCtx interface{}) *MockAdapter_DeleteStaticAccessToken_Call {
	return &MockAdapter_DeleteStaticAccessToken_Call{Call: _e.mock.On("DeleteStaticAccessToken", ctx, reqCtx)}
}

func (_c *MockAdapter_DeleteStaticAccessToken_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_DeleteStaticAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_DeleteStaticAccessToken_Call) Return() *MockAdapter_DeleteStaticAccessToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_DeleteStaticAccessToken_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_DeleteStaticAccessToken_Call {
	_c.Run(run)
	return _c
}

// FilterStaticAccessTokens provides a mock function for the type MockAdapter
func (_mock *MockAdapter) FilterStaticAccessTokens(ctx context.Context, reqCtx *server.RequestContext, req *FilterStaticAccessTokenRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_FilterStaticAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterStaticAccessTokens'
type MockAdapter_FilterStaticAccessTokens_Call struct {
	*mock.Call
}

// FilterStaticAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *FilterStaticAccessTokenRequest
func (_e *MockAdapter_Expecter) FilterStaticAccessTokens(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_FilterStaticAccessTokens_Call {
	return &MockAdapter_FilterStaticAccessTokens_Call{Call: _e.mock.On("FilterStaticAccessTokens", ctx, reqCtx, req)}
}

func (_c *MockAdapter_FilterStaticAccessTokens_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *FilterStaticAccessTokenRequest)) *MockAdapter_FilterStaticAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *FilterStaticAccessTokenRequest
		if args[2] != nil {
			arg2 = args[2].(*FilterStaticAccessTokenRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_FilterStaticAccessTokens_Call) Return() *MockAdapter_FilterStaticAccessTokens_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_FilterStaticAccessTokens_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *FilterStaticAccessTokenRequest)) *MockAdapter_FilterStaticAccessTokens_Call {
	_c.Run(run)
	return _c
}

// TokenAuthorizeHTTP provides a mock function for the type MockAdapter
func (_mock *MockAdapter) TokenAuthorizeHTTP(ctx context.Context, reqCtx *server.RequestContext, req *TokenAuthorizeHTTPRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_TokenAuthorizeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenAuthorizeHTTP'
type MockAdapter_TokenAuthorizeHTTP_Call struct {
	*mock.Call
}

// TokenAuthorizeHTTP is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *TokenAuthorizeHTTPRequest
func (_e *MockAdapter_Expecter) TokenAuthorizeHTTP(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_TokenAuthorizeHTTP_Call {
	return &MockAdapter_TokenAuthorizeHTTP_Call{Call: _e.mock.On("TokenAuthorizeHTTP", ctx, reqCtx, req)}
}

func (_c *MockAdapter_TokenAuthorizeHTTP_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *TokenAuthorizeHTTPRequest)) *MockAdapter_TokenAuthorizeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *TokenAuthorizeHTTPRequest
		if args[2] != nil {
			arg2 = args[2].(*TokenAuthorizeHTTPRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_TokenAuthorizeHTTP_Call) Return() *MockAdapter_TokenAuthorizeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_TokenAuthorizeHTTP_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *TokenAuthorizeHTTPRequest)) *MockAdapter_TokenAuthorizeHTTP_Call {
	_c.Run(run)
	return _c
}

// TokenRenew provides a mock function for the type MockAdapter
func (_mock *MockAdapter) TokenRenew(ctx context.Context, reqCtx *server.RequestContext, req *TokenRenewRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_TokenRenew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenRenew'
type MockAdapter_TokenRenew_Call struct {
	*mock.Call
}

// TokenRenew is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *TokenRenewRequest
func (_e *MockAdapter_Expecter) TokenRenew(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_TokenRenew_Call {
	return &MockAdapter_TokenRenew_Call{Call: _e.mock.On("TokenRenew", ctx, reqCtx, req)}
}

func (_c *MockAdapter_TokenRenew_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *TokenRenewRequest)) *MockAdapter_TokenRenew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *TokenRenewRequest
		if args[2] != nil {
			arg2 = args[2].(*TokenRenewRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_TokenRenew_Call) Return() *MockAdapter_TokenRenew_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_TokenRenew_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *TokenRenewRequest)) *MockAdapter_TokenRenew_Call {
	_c.Run(run)
	return _c
}

// TokenValidate provides a mock function for the type MockAdapter
func (_mock *MockAdapter) TokenValidate(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_TokenValidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenValidate'
type MockAdapter_TokenValidate_Call struct {
	*mock.Call
}

// TokenValidate is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) TokenValidate(ctx interface{}, reqCtx interface{}) *MockAdapter_TokenValidate_Call {
	return &MockAdapter_TokenValidate_Call{Call: _e.mock.On("TokenValidate", ctx, reqCtx)}
}

func (_c *MockAdapter_TokenValidate_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_TokenValidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_TokenValidate_Call) Return() *MockAdapter_TokenValidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_TokenValidate_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_TokenValidate_Call {
	_c.Run(run)
	return _c
}
