// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"fmt"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/auth"
	"go.microcore.dev/auth-service/internal/shared/postgres"
	"go.microcore.dev/auth-service/internal/shared/redis"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (auth.Adapter, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	logger := newLogger()
	localTokenCache, err := newLocalTokenCache(config)
	if err != nil {
		return nil, err
	}
	authAdapter := newAdapter(opts, config, logger, localTokenCache)
	return authAdapter, nil
}

// wire.go:

type (
	Options struct {
		Postgres *postgres.Postgres
		Redis    *redis.Redis
	}
)

func newLogger() *slog.Logger {
	return log.New("repository/auth")
}

func newLocalTokenCache(
	config *Config,
) (*LocalTokenCache, error) {
	cache, err := NewLocalTokenCache(config.Cache.LocalTokenSize)
	if err != nil {
		return nil, fmt.Errorf("local token cache: %w", err)
	}
	return cache, nil
}

func newAdapter(
	opts *Options,
	config *Config,
	logger *slog.Logger,
	localTokenCache *LocalTokenCache,
) auth.Adapter {
	return NewAdapter(
		&AdapterConfig{
			Config:          config,
			Logger:          logger,
			Redis:           opts.Redis,
			Postgres:        opts.Postgres,
			LocalTokenCache: localTokenCache,
		},
	)
}
