// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"context"
	"fmt"
	"go.microcore.dev/auth-service/internal/shared/postgres"
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(ctx context.Context, opts *Options) (*Migrate, error) {
	config := NewConfig()
	logger := newLogger(config)
	telemetry, err := newTelemetry(ctx, config)
	if err != nil {
		return nil, err
	}
	postgres, err := newPostgres(telemetry)
	if err != nil {
		return nil, err
	}
	migrate := newMigrate(config, logger, telemetry, postgres)
	return migrate, nil
}

// wire.go:

func newLogger(
	cfg *Config,
) *slog.Logger {
	return log.New(cfg.Name)
}

func newTelemetry(
	ctx context.Context,
	cfg *Config,
) (*telemetry.Telemetry, error) {
	t, err := telemetry.Init(
		ctx,
		&telemetry.Options{
			AppName: cfg.Name,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init telemetry: %w", err)
	}
	return t, nil
}

func newPostgres(telemetry2 *telemetry.Telemetry,
) (*postgres.Postgres, error) {
	p, err := postgres.Init(
		&postgres.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init postgres: %w", err)
	}
	if err := p.Setup(); err != nil {
		return nil, fmt.Errorf("setup postgres: %w", err)
	}
	return p, nil
}

func newMigrate(
	config *Config,
	logger *slog.Logger, telemetry2 *telemetry.Telemetry, postgres2 *postgres.Postgres,
) *Migrate {
	return &Migrate{
		Config:    config,
		Logger:    logger,
		Telemetry: telemetry2,
		Postgres:  postgres2,
	}
}
