// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"fmt"
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(ctx context.Context, opts *Options) (*Bootstrap, error) {
	config := NewConfig()
	logger := newLogger(config)
	telemetry, err := newTelemetry(ctx, config)
	if err != nil {
		return nil, err
	}
	bootstrap := newBootstrap(opts, config, logger, telemetry)
	return bootstrap, nil
}

// wire.go:

func newLogger(
	cfg *Config,
) *slog.Logger {
	return log.New(cfg.Name)
}

func newTelemetry(
	ctx context.Context,
	cfg *Config,
) (*telemetry.Telemetry, error) {
	t, err := telemetry.Init(
		ctx,
		&telemetry.Options{
			AppName: cfg.Name,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init telemetry: %w", err)
	}
	return t, nil
}

func newBootstrap(
	options *Options,
	config *Config,
	logger *slog.Logger, telemetry2 *telemetry.Telemetry,
) *Bootstrap {
	return &Bootstrap{
		Options:   options,
		Config:    config,
		Logger:    logger,
		Telemetry: telemetry2,
	}
}
