// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/transport/http/server"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// CreateHTTPRule provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CreateHTTPRule(ctx context.Context, reqCtx *server.RequestContext, req *CreateHTTPRuleRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_CreateHTTPRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHTTPRule'
type MockAdapter_CreateHTTPRule_Call struct {
	*mock.Call
}

// CreateHTTPRule is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *CreateHTTPRuleRequest
func (_e *MockAdapter_Expecter) CreateHTTPRule(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_CreateHTTPRule_Call {
	return &MockAdapter_CreateHTTPRule_Call{Call: _e.mock.On("CreateHTTPRule", ctx, reqCtx, req)}
}

func (_c *MockAdapter_CreateHTTPRule_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *CreateHTTPRuleRequest)) *MockAdapter_CreateHTTPRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *CreateHTTPRuleRequest
		if args[2] != nil {
			arg2 = args[2].(*CreateHTTPRuleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_CreateHTTPRule_Call) Return() *MockAdapter_CreateHTTPRule_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_CreateHTTPRule_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *CreateHTTPRuleRequest)) *MockAdapter_CreateHTTPRule_Call {
	_c.Run(run)
	return _c
}

// DeleteHTTPRule provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DeleteHTTPRule(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_DeleteHTTPRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHTTPRule'
type MockAdapter_DeleteHTTPRule_Call struct {
	*mock.Call
}

// DeleteHTTPRule is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) DeleteHTTPRule(ctx interface{}, reqCtx interface{}) *MockAdapter_DeleteHTTPRule_Call {
	return &MockAdapter_DeleteHTTPRule_Call{Call: _e.mock.On("DeleteHTTPRule", ctx, reqCtx)}
}

func (_c *MockAdapter_DeleteHTTPRule_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_DeleteHTTPRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_DeleteHTTPRule_Call) Return() *MockAdapter_DeleteHTTPRule_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_DeleteHTTPRule_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_DeleteHTTPRule_Call {
	_c.Run(run)
	return _c
}

// FilterHTTPRules provides a mock function for the type MockAdapter
func (_mock *MockAdapter) FilterHTTPRules(ctx context.Context, reqCtx *server.RequestContext, req *FilterHTTPRulesRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_FilterHTTPRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterHTTPRules'
type MockAdapter_FilterHTTPRules_Call struct {
	*mock.Call
}

// FilterHTTPRules is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *FilterHTTPRulesRequest
func (_e *MockAdapter_Expecter) FilterHTTPRules(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_FilterHTTPRules_Call {
	return &MockAdapter_FilterHTTPRules_Call{Call: _e.mock.On("FilterHTTPRules", ctx, reqCtx, req)}
}

func (_c *MockAdapter_FilterHTTPRules_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *FilterHTTPRulesRequest)) *MockAdapter_FilterHTTPRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *FilterHTTPRulesRequest
		if args[2] != nil {
			arg2 = args[2].(*FilterHTTPRulesRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_FilterHTTPRules_Call) Return() *MockAdapter_FilterHTTPRules_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_FilterHTTPRules_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *FilterHTTPRulesRequest)) *MockAdapter_FilterHTTPRules_Call {
	_c.Run(run)
	return _c
}

// UpdateHTTPRule provides a mock function for the type MockAdapter
func (_mock *MockAdapter) UpdateHTTPRule(ctx context.Context, reqCtx *server.RequestContext, req *UpdateHTTPRuleRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_UpdateHTTPRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHTTPRule'
type MockAdapter_UpdateHTTPRule_Call struct {
	*mock.Call
}

// UpdateHTTPRule is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *UpdateHTTPRuleRequest
func (_e *MockAdapter_Expecter) UpdateHTTPRule(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_UpdateHTTPRule_Call {
	return &MockAdapter_UpdateHTTPRule_Call{Call: _e.mock.On("UpdateHTTPRule", ctx, reqCtx, req)}
}

func (_c *MockAdapter_UpdateHTTPRule_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *UpdateHTTPRuleRequest)) *MockAdapter_UpdateHTTPRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *UpdateHTTPRuleRequest
		if args[2] != nil {
			arg2 = args[2].(*UpdateHTTPRuleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_UpdateHTTPRule_Call) Return() *MockAdapter_UpdateHTTPRule_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_UpdateHTTPRule_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *UpdateHTTPRuleRequest)) *MockAdapter_UpdateHTTPRule_Call {
	_c.Run(run)
	return _c
}
