// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package devices

import (
	"go.microcore.dev/auth-service/internal/port/adapter/repository/auth"
	"go.microcore.dev/auth-service/internal/port/service/devices"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (devices.Service, error) {
	logger := newLogger()
	devicesService := newService(opts, logger)
	return devicesService, nil
}

// wire.go:

type (
	Options struct {
		AuthRepository auth.Adapter
	}
)

func newLogger() *slog.Logger {
	return log.New("service/devices")
}

func newService(
	opts *Options,
	logger *slog.Logger,
) devices.Service {
	return NewService(
		&ServiceConfig{
			Logger:         logger,
			AuthRepository: opts.AuthRepository,
		},
	)
}
