// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package log

import (
	"io"
)

// Injectors from wire.go:

func Init(opts *Options) (*Log, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	log := newLog(opts, config)
	return log, nil
}

// wire.go:

type Options struct {
	Stderr io.Writer
}

func newLog(
	opts *Options,
	config *Config,
) *Log {
	return &Log{
		Config: config,
		Stderr: opts.Stderr,
	}
}
