// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package telemetry

import (
	"context"
	"fmt"
	"go.microcore.dev/framework/shutdown"
	"go.microcore.dev/framework/telemetry"
)

// Injectors from wire.go:

func Init(ctx context.Context, opts *Options) (*Telemetry, error) {
	config := NewConfig()
	manager, err := newManager(ctx, config, opts)
	if err != nil {
		return nil, err
	}
	telemetry := newTelemetry(opts, config, manager)
	return telemetry, nil
}

// wire.go:

func newManager(
	ctx context.Context,
	config *Config,
	opts *Options,
) (telemetry.Manager, error) {
	if config.Enabled {
		manager, err := telemetry.NewDefaultInsecureOtlpGrpc(
			ctx,
			config.Endpoint,
			opts.AppName,
		)
		if err != nil {
			return nil, shutdown.NewExitReason(shutdown.ExitUnavailable, fmt.Errorf("create telemetry manager: %w", err))
		}
		return manager, nil
	}
	return nil, nil
}

func newTelemetry(
	options *Options,
	config *Config,
	manager telemetry.Manager,
) *Telemetry {
	return &Telemetry{
		Options: options,
		Config:  config,
		Manager: manager,
	}
}
