// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package roles

import (
	roles2 "go.microcore.dev/auth-service/internal/port/adapter/repository/roles"
	"go.microcore.dev/auth-service/internal/port/service/roles"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (roles.Service, error) {
	logger := newLogger()
	rolesService := newService(opts, logger)
	return rolesService, nil
}

// wire.go:

type (
	Options struct {
		RolesRepository roles2.Adapter
	}
)

func newLogger() *slog.Logger {
	return log.New("service/roles")
}

func newService(
	opts *Options,
	logger *slog.Logger,
) roles.Service {
	return NewService(
		&ServiceConfig{
			Logger:          logger,
			RolesRepository: opts.RolesRepository,
		},
	)
}
