// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logout

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// LogoutAll provides a mock function for the type MockService
func (_mock *MockService) LogoutAll(ctx context.Context, data AllData) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AllData) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockService_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - data AllData
func (_e *MockService_Expecter) LogoutAll(ctx interface{}, data interface{}) *MockService_LogoutAll_Call {
	return &MockService_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, data)}
}

func (_c *MockService_LogoutAll_Call) Run(run func(ctx context.Context, data AllData)) *MockService_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AllData
		if args[1] != nil {
			arg1 = args[1].(AllData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_LogoutAll_Call) Return(err error) *MockService_LogoutAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LogoutAll_Call) RunAndReturn(run func(ctx context.Context, data AllData) error) *MockService_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutDevice provides a mock function for the type MockService
func (_mock *MockService) LogoutDevice(ctx context.Context, data DeviceData) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for LogoutDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DeviceData) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LogoutDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutDevice'
type MockService_LogoutDevice_Call struct {
	*mock.Call
}

// LogoutDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - data DeviceData
func (_e *MockService_Expecter) LogoutDevice(ctx interface{}, data interface{}) *MockService_LogoutDevice_Call {
	return &MockService_LogoutDevice_Call{Call: _e.mock.On("LogoutDevice", ctx, data)}
}

func (_c *MockService_LogoutDevice_Call) Run(run func(ctx context.Context, data DeviceData)) *MockService_LogoutDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DeviceData
		if args[1] != nil {
			arg1 = args[1].(DeviceData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_LogoutDevice_Call) Return(err error) *MockService_LogoutDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LogoutDevice_Call) RunAndReturn(run func(ctx context.Context, data DeviceData) error) *MockService_LogoutDevice_Call {
	_c.Call.Return(run)
	return _c
}
