// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
	"fmt"
	http2 "go.microcore.dev/auth-service/internal/adapter/handler/auth/http"
	http4 "go.microcore.dev/auth-service/internal/adapter/handler/devices/http"
	http6 "go.microcore.dev/auth-service/internal/adapter/handler/logout/http"
	http8 "go.microcore.dev/auth-service/internal/adapter/handler/roles/http"
	http10 "go.microcore.dev/auth-service/internal/adapter/handler/rules/http"
	http12 "go.microcore.dev/auth-service/internal/adapter/handler/tokens/http"
	auth2 "go.microcore.dev/auth-service/internal/adapter/repository/auth"
	roles2 "go.microcore.dev/auth-service/internal/adapter/repository/roles"
	rules2 "go.microcore.dev/auth-service/internal/adapter/repository/rules"
	"go.microcore.dev/auth-service/internal/port/adapter/handler/auth/http"
	http3 "go.microcore.dev/auth-service/internal/port/adapter/handler/devices/http"
	http5 "go.microcore.dev/auth-service/internal/port/adapter/handler/logout/http"
	http7 "go.microcore.dev/auth-service/internal/port/adapter/handler/roles/http"
	http9 "go.microcore.dev/auth-service/internal/port/adapter/handler/rules/http"
	http11 "go.microcore.dev/auth-service/internal/port/adapter/handler/tokens/http"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/auth"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/roles"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/rules"
	"go.microcore.dev/auth-service/internal/port/service/devices"
	"go.microcore.dev/auth-service/internal/port/service/logout"
	roles3 "go.microcore.dev/auth-service/internal/port/service/roles"
	rules3 "go.microcore.dev/auth-service/internal/port/service/rules"
	"go.microcore.dev/auth-service/internal/port/service/tokens"
	devices2 "go.microcore.dev/auth-service/internal/service/devices"
	logout2 "go.microcore.dev/auth-service/internal/service/logout"
	roles4 "go.microcore.dev/auth-service/internal/service/roles"
	rules4 "go.microcore.dev/auth-service/internal/service/rules"
	tokens2 "go.microcore.dev/auth-service/internal/service/tokens"
	"go.microcore.dev/auth-service/internal/shared/http/server"
	"go.microcore.dev/auth-service/internal/shared/postgres"
	"go.microcore.dev/auth-service/internal/shared/redis"
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/log"
	"log/slog"
)

import (
	_ "go.microcore.dev/auth-service/docs"
)

// Injectors from wire.go:

func Init(ctx context.Context, opts *Options) (*Server, error) {
	config := NewConfig()
	logger := newLogger(config)
	telemetry, err := newTelemetry(ctx, config)
	if err != nil {
		return nil, err
	}
	postgres, err := newPostgres(telemetry)
	if err != nil {
		return nil, err
	}
	redis, err := newRedis(telemetry)
	if err != nil {
		return nil, err
	}
	server, err := newHTTPServer(telemetry)
	if err != nil {
		return nil, err
	}
	adapter, err := newRolesRepository(postgres, redis)
	if err != nil {
		return nil, err
	}
	authAdapter, err := newAuthRepository(postgres, redis)
	if err != nil {
		return nil, err
	}
	service, err := newTokensService(authAdapter)
	if err != nil {
		return nil, err
	}
	rolesService, err := newRolesService(adapter)
	if err != nil {
		return nil, err
	}
	httpAdapter, err := newAuthHandler(service, rolesService)
	if err != nil {
		return nil, err
	}
	devicesService, err := newDevicesService(authAdapter)
	if err != nil {
		return nil, err
	}
	adapter2, err := newDevicesHandler(devicesService)
	if err != nil {
		return nil, err
	}
	logoutService, err := newLogoutService(authAdapter)
	if err != nil {
		return nil, err
	}
	adapter3, err := newLogoutHandler(logoutService)
	if err != nil {
		return nil, err
	}
	adapter4, err := newRolesHandler(rolesService)
	if err != nil {
		return nil, err
	}
	rulesAdapter, err := newRulesRepository(postgres, redis)
	if err != nil {
		return nil, err
	}
	rulesService, err := newRulesService(rulesAdapter)
	if err != nil {
		return nil, err
	}
	adapter5, err := newRulesHandler(rulesService)
	if err != nil {
		return nil, err
	}
	adapter6, err := newTokensHandler(service, rolesService)
	if err != nil {
		return nil, err
	}
	serverServer := newServer(config, logger, telemetry, postgres, redis, server, adapter, httpAdapter, adapter2, adapter3, adapter4, adapter5, adapter6)
	return serverServer, nil
}

// wire.go:

func newLogger(
	cfg *Config,
) *slog.Logger {
	return log.New(cfg.Name)
}

func newTelemetry(
	ctx context.Context,
	cfg *Config,
) (*telemetry.Telemetry, error) {
	t, err := telemetry.Init(
		ctx,
		&telemetry.Options{
			AppName: cfg.Name,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init telemetry: %w", err)
	}
	return t, nil
}

func newPostgres(telemetry2 *telemetry.Telemetry,
) (*postgres.Postgres, error) {
	p, err := postgres.Init(
		&postgres.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init postgres: %w", err)
	}
	if err := p.Setup(); err != nil {
		return nil, fmt.Errorf("setup postgres: %w", err)
	}
	return p, nil
}

func newRedis(telemetry2 *telemetry.Telemetry,
) (*redis.Redis, error) {
	p, err := redis.Init(
		&redis.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init redis: %w", err)
	}
	if err := p.Setup(); err != nil {
		return nil, fmt.Errorf("setup redis: %w", err)
	}
	return p, nil
}

func newHTTPServer(telemetry2 *telemetry.Telemetry,
) (*server.Server, error) {
	s, err := server.Init(
		&server.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init http server: %w", err)
	}
	s.Setup()
	return s, nil
}

func newAuthRepository(postgres2 *postgres.Postgres, redis2 *redis.Redis,
) (auth.Adapter, error) {
	r, err := auth2.Init(
		&auth2.Options{
			Postgres: postgres2,
			Redis:    redis2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init auth repository: %w", err)
	}
	return r, nil
}

func newRolesRepository(postgres2 *postgres.Postgres, redis2 *redis.Redis,
) (roles.Adapter, error) {
	r, err := roles2.Init(
		&roles2.Options{
			Postgres: postgres2,
			Redis:    redis2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init roles repository: %w", err)
	}
	return r, nil
}

func newRulesRepository(postgres2 *postgres.Postgres, redis2 *redis.Redis,
) (rules.Adapter, error) {
	r, err := rules2.Init(
		&rules2.Options{
			Postgres: postgres2,
			Redis:    redis2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init rules repository: %w", err)
	}
	return r, nil
}

func newTokensService(
	authRepository auth.Adapter,
) (tokens.Service, error) {
	s, err := tokens2.Init(
		&tokens2.Options{
			AuthRepository: authRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init tokens service: %w", err)
	}
	return s, nil
}

func newRulesService(
	rulesRepository rules.Adapter,
) (rules3.Service, error) {
	s, err := rules4.Init(
		&rules4.Options{
			RulesRepository: rulesRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init rules service: %w", err)
	}
	return s, nil
}

func newRolesService(
	rolesRepository roles.Adapter,
) (roles3.Service, error) {
	s, err := roles4.Init(
		&roles4.Options{
			RolesRepository: rolesRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init roles service: %w", err)
	}
	return s, nil
}

func newDevicesService(
	authRepository auth.Adapter,
) (devices.Service, error) {
	s, err := devices2.Init(
		&devices2.Options{
			AuthRepository: authRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init devices service: %w", err)
	}
	return s, nil
}

func newLogoutService(
	authRepository auth.Adapter,
) (logout.Service, error) {
	s, err := logout2.Init(
		&logout2.Options{
			AuthRepository: authRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init logout service: %w", err)
	}
	return s, nil
}

func newAuthHandler(
	tokensService tokens.Service,
	rolesService roles3.Service,
) (http.Adapter, error) {
	h, err := http2.Init(
		&http2.Options{
			TokensService: tokensService,
			RolesService:  rolesService,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init auth handler: %w", err)
	}
	return h, nil
}

func newDevicesHandler(
	devicesService devices.Service,
) (http3.Adapter, error) {
	h, err := http4.Init(
		&http4.Options{
			DevicesService: devicesService,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init devices handler: %w", err)
	}
	return h, nil
}

func newLogoutHandler(
	logoutService logout.Service,
) (http5.Adapter, error) {
	h, err := http6.Init(
		&http6.Options{
			LogoutService: logoutService,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init logout handler: %w", err)
	}
	return h, nil
}

func newRolesHandler(
	rolesService roles3.Service,
) (http7.Adapter, error) {
	h, err := http8.Init(
		&http8.Options{
			RolesService: rolesService,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init roles handler: %w", err)
	}
	return h, nil
}

func newRulesHandler(
	rulesService rules3.Service,
) (http9.Adapter, error) {
	h, err := http10.Init(
		&http10.Options{
			RulesService: rulesService,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init rules handler: %w", err)
	}
	return h, nil
}

func newTokensHandler(
	tokensService tokens.Service,
	rolesService roles3.Service,
) (http11.Adapter, error) {
	h, err := http12.Init(
		&http12.Options{
			TokensService: tokensService,
			RolesService:  rolesService,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init tokens handler: %w", err)
	}
	return h, nil
}

func newServer(
	config *Config,
	logger *slog.Logger, telemetry2 *telemetry.Telemetry, postgres2 *postgres.Postgres, redis2 *redis.Redis,
	httpServer *server.Server,

	rolesRepository roles.Adapter,

	authHandler http.Adapter,
	devicesHandler http3.Adapter,
	logoutHandler http5.Adapter,
	rolesHandler http7.Adapter,
	rulesHandler http9.Adapter,
	tokensHandler http11.Adapter,
) *Server {
	return &Server{
		Config:     config,
		Logger:     logger,
		Telemetry:  telemetry2,
		Postgres:   postgres2,
		Redis:      redis2,
		HTTPServer: httpServer,
		Repository: &Repository{
			Roles: rolesRepository,
		},
		Handler: &Handler{
			Auth:    authHandler,
			Devices: devicesHandler,
			Logout:  logoutHandler,
			Roles:   rolesHandler,
			Rules:   rulesHandler,
			Tokens:  tokensHandler,
		},
	}
}
