// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"fmt"
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/shutdown"
	"go.microcore.dev/framework/transport/http/server"
	"go.microcore.dev/framework/transport/http/server/core"
	"go.microcore.dev/framework/transport/http/server/listener"
)

// Injectors from wire.go:

func Init(opts *Options) (*Server, error) {
	config := NewConfig()
	manager, err := newManager(config)
	if err != nil {
		return nil, err
	}
	server := newServer(config, opts, manager)
	return server, nil
}

// wire.go:

type (
	Options struct {
		Telemetry *telemetry.Telemetry
	}
)

func newManager(
	config *Config,
) (server.Manager, error) {
	manager, err := server.New(server.WithListenerOptions(listener.WithHostname(config.Host), listener.WithPort(config.Port)), server.WithCoreOptions(core.WithName(config.Name), core.WithConcurrency(config.Concurrency), core.WithReadBufferSize(config.ReadBufferSize), core.WithWriteBufferSize(config.WriteBufferSize), core.WithReadTimeout(config.ReadTimeout), core.WithWriteTimeout(config.WriteTimeout), core.WithIdleTimeout(config.IdleTimeout), core.WithMaxConnsPerIP(config.MaxConnsPerIP), core.WithMaxRequestsPerConn(config.MaxRequestsPerConn), core.WithMaxRequestBodySize(config.MaxRequestBodySize), core.WithDisableKeepalive(config.DisableKeepalive), core.WithTCPKeepalive(config.TCPKeepalive), core.WithLogAllErrors(config.LogAllErrors)),
	)
	if err != nil {
		return nil, shutdown.NewExitReason(shutdown.ExitOSError, fmt.Errorf("create http server manager: %w", err))
	}
	return manager, nil
}

func newServer(
	config *Config,
	opts *Options,
	manager server.Manager,
) *Server {
	return &Server{
		Config:    config,
		Telemetry: opts.Telemetry,
		Manager:   manager,
	}
}
