// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package seed

import (
	"context"
	"fmt"
	auth2 "go.microcore.dev/auth-service/internal/adapter/repository/auth"
	roles2 "go.microcore.dev/auth-service/internal/adapter/repository/roles"
	rules2 "go.microcore.dev/auth-service/internal/adapter/repository/rules"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/auth"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/roles"
	"go.microcore.dev/auth-service/internal/port/adapter/repository/rules"
	roles3 "go.microcore.dev/auth-service/internal/port/service/roles"
	rules3 "go.microcore.dev/auth-service/internal/port/service/rules"
	"go.microcore.dev/auth-service/internal/port/service/tokens"
	roles4 "go.microcore.dev/auth-service/internal/service/roles"
	rules4 "go.microcore.dev/auth-service/internal/service/rules"
	tokens2 "go.microcore.dev/auth-service/internal/service/tokens"
	"go.microcore.dev/auth-service/internal/shared/http/client"
	"go.microcore.dev/auth-service/internal/shared/postgres"
	"go.microcore.dev/auth-service/internal/shared/redis"
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(ctx context.Context, opts *Options) (*Seed, error) {
	config := NewConfig()
	logger := newLogger(config)
	telemetry, err := newTelemetry(ctx, opts, config)
	if err != nil {
		return nil, err
	}
	postgres, err := newPostgres(telemetry)
	if err != nil {
		return nil, err
	}
	redis, err := newRedis(telemetry)
	if err != nil {
		return nil, err
	}
	client, err := newHTTPClient(telemetry)
	if err != nil {
		return nil, err
	}
	adapter, err := newAuthRepository(postgres, redis)
	if err != nil {
		return nil, err
	}
	service, err := newTokensService(adapter)
	if err != nil {
		return nil, err
	}
	rolesAdapter, err := newRolesRepository(postgres, redis)
	if err != nil {
		return nil, err
	}
	rolesService, err := newRolesService(rolesAdapter)
	if err != nil {
		return nil, err
	}
	rulesAdapter, err := newRulesRepository(postgres, redis)
	if err != nil {
		return nil, err
	}
	rulesService, err := newRulesService(rulesAdapter)
	if err != nil {
		return nil, err
	}
	seed := newSeed(opts, config, logger, telemetry, postgres, redis, client, service, rolesService, rulesService)
	return seed, nil
}

// wire.go:

func newLogger(
	cfg *Config,
) *slog.Logger {
	return log.New(cfg.Name)
}

func newTelemetry(
	ctx context.Context,
	opts *Options,
	cfg *Config,
) (*telemetry.Telemetry, error) {
	t, err := telemetry.Init(
		ctx,
		&telemetry.Options{
			AppName: cfg.Name,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init telemetry: %w", err)
	}
	return t, nil
}

func newPostgres(telemetry2 *telemetry.Telemetry,
) (*postgres.Postgres, error) {
	p, err := postgres.Init(
		&postgres.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init postgres: %w", err)
	}
	if err := p.Setup(); err != nil {
		return nil, fmt.Errorf("setup postgres: %w", err)
	}
	return p, nil
}

func newRedis(telemetry2 *telemetry.Telemetry,
) (*redis.Redis, error) {
	p, err := redis.Init(
		&redis.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init redis: %w", err)
	}
	if err := p.Setup(); err != nil {
		return nil, fmt.Errorf("setup redis: %w", err)
	}
	return p, nil
}

func newHTTPClient(telemetry2 *telemetry.Telemetry,
) (*client.Client, error) {
	c, err := client.Init(
		&client.Options{
			Telemetry: telemetry2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init http client: %w", err)
	}
	c.Setup()
	return c, nil
}

func newAuthRepository(postgres2 *postgres.Postgres, redis2 *redis.Redis,
) (auth.Adapter, error) {
	r, err := auth2.Init(
		&auth2.Options{
			Postgres: postgres2,
			Redis:    redis2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init auth repository: %w", err)
	}
	return r, nil
}

func newRolesRepository(postgres2 *postgres.Postgres, redis2 *redis.Redis,
) (roles.Adapter, error) {
	r, err := roles2.Init(
		&roles2.Options{
			Postgres: postgres2,
			Redis:    redis2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init roles repository: %w", err)
	}
	return r, nil
}

func newRulesRepository(postgres2 *postgres.Postgres, redis2 *redis.Redis,
) (rules.Adapter, error) {
	r, err := rules2.Init(
		&rules2.Options{
			Postgres: postgres2,
			Redis:    redis2,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init rules repository: %w", err)
	}
	return r, nil
}

func newTokensService(
	authRepository auth.Adapter,
) (tokens.Service, error) {
	s, err := tokens2.Init(
		&tokens2.Options{
			AuthRepository: authRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init tokens service: %w", err)
	}
	return s, nil
}

func newRulesService(
	rulesRepository rules.Adapter,
) (rules3.Service, error) {
	s, err := rules4.Init(
		&rules4.Options{
			RulesRepository: rulesRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init rules service: %w", err)
	}
	return s, nil
}

func newRolesService(
	rolesRepository roles.Adapter,
) (roles3.Service, error) {
	s, err := roles4.Init(
		&roles4.Options{
			RolesRepository: rolesRepository,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("init roles service: %w", err)
	}
	return s, nil
}

func newSeed(
	options *Options,
	config *Config,
	logger *slog.Logger, telemetry2 *telemetry.Telemetry, postgres2 *postgres.Postgres, redis2 *redis.Redis,
	httpClient *client.Client,
	tokensService tokens.Service,
	rolesService roles3.Service,
	rulesService rules3.Service,
) *Seed {
	return &Seed{
		Options:    options,
		Config:     config,
		Logger:     logger,
		Telemetry:  telemetry2,
		Postgres:   postgres2,
		Redis:      redis2,
		HTTPClient: httpClient,
		Service: &Service{
			Tokens: tokensService,
			Roles:  rolesService,
			Rules:  rulesService,
		},
	}
}
