// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http

import (
	"go.microcore.dev/auth-service/internal/port/adapter/handler/roles/http"
	"go.microcore.dev/auth-service/internal/port/service/roles"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (http.Adapter, error) {
	logger := newLogger()
	httpAdapter := newHandler(opts, logger)
	return httpAdapter, nil
}

// wire.go:

type Options struct {
	RolesService roles.Service
}

func newLogger() *slog.Logger {
	return log.New("handler/roles")
}

func newHandler(
	opts *Options,
	logger *slog.Logger,
) http.Adapter {
	return NewAdapter(
		&AdapterConfig{
			Logger:       logger,
			RolesService: opts.RolesService,
		},
	)
}
