// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logout

import (
	"go.microcore.dev/auth-service/internal/port/adapter/repository/auth"
	"go.microcore.dev/auth-service/internal/port/service/logout"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (logout.Service, error) {
	logger := newLogger()
	logoutService := newService(opts, logger)
	return logoutService, nil
}

// wire.go:

type (
	Options struct {
		AuthRepository auth.Adapter
	}
)

func newLogger() *slog.Logger {
	return log.New("service/logout")
}

func newService(
	opts *Options,
	logger *slog.Logger,
) logout.Service {
	return NewService(
		&ServiceConfig{
			Logger:         logger,
			AuthRepository: opts.AuthRepository,
		},
	)
}
