// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package roles

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// AuthorizeHTTPRoles provides a mock function for the type MockAdapter
func (_mock *MockAdapter) AuthorizeHTTPRoles(ctx context.Context, data AuthorizeHTTPRolesData) (*AuthorizeHTTPRolesResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeHTTPRoles")
	}

	var r0 *AuthorizeHTTPRolesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuthorizeHTTPRolesData) (*AuthorizeHTTPRolesResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuthorizeHTTPRolesData) *AuthorizeHTTPRolesResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthorizeHTTPRolesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AuthorizeHTTPRolesData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_AuthorizeHTTPRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeHTTPRoles'
type MockAdapter_AuthorizeHTTPRoles_Call struct {
	*mock.Call
}

// AuthorizeHTTPRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - data AuthorizeHTTPRolesData
func (_e *MockAdapter_Expecter) AuthorizeHTTPRoles(ctx interface{}, data interface{}) *MockAdapter_AuthorizeHTTPRoles_Call {
	return &MockAdapter_AuthorizeHTTPRoles_Call{Call: _e.mock.On("AuthorizeHTTPRoles", ctx, data)}
}

func (_c *MockAdapter_AuthorizeHTTPRoles_Call) Run(run func(ctx context.Context, data AuthorizeHTTPRolesData)) *MockAdapter_AuthorizeHTTPRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AuthorizeHTTPRolesData
		if args[1] != nil {
			arg1 = args[1].(AuthorizeHTTPRolesData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_AuthorizeHTTPRoles_Call) Return(authorizeHTTPRolesResult *AuthorizeHTTPRolesResult, err error) *MockAdapter_AuthorizeHTTPRoles_Call {
	_c.Call.Return(authorizeHTTPRolesResult, err)
	return _c
}

func (_c *MockAdapter_AuthorizeHTTPRoles_Call) RunAndReturn(run func(ctx context.Context, data AuthorizeHTTPRolesData) (*AuthorizeHTTPRolesResult, error)) *MockAdapter_AuthorizeHTTPRoles_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CreateRole(ctx context.Context, data CreateRoleData) (*CreateRoleResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *CreateRoleResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRoleData) (*CreateRoleResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRoleData) *CreateRoleResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateRoleResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateRoleData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockAdapter_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - data CreateRoleData
func (_e *MockAdapter_Expecter) CreateRole(ctx interface{}, data interface{}) *MockAdapter_CreateRole_Call {
	return &MockAdapter_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, data)}
}

func (_c *MockAdapter_CreateRole_Call) Run(run func(ctx context.Context, data CreateRoleData)) *MockAdapter_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateRoleData
		if args[1] != nil {
			arg1 = args[1].(CreateRoleData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_CreateRole_Call) Return(createRoleResult *CreateRoleResult, err error) *MockAdapter_CreateRole_Call {
	_c.Call.Return(createRoleResult, err)
	return _c
}

func (_c *MockAdapter_CreateRole_Call) RunAndReturn(run func(ctx context.Context, data CreateRoleData) (*CreateRoleResult, error)) *MockAdapter_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DeleteRole(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockAdapter_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdapter_Expecter) DeleteRole(ctx interface{}, id interface{}) *MockAdapter_DeleteRole_Call {
	return &MockAdapter_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, id)}
}

func (_c *MockAdapter_DeleteRole_Call) Run(run func(ctx context.Context, id string)) *MockAdapter_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_DeleteRole_Call) Return(err error) *MockAdapter_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAdapter_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// FilterRoles provides a mock function for the type MockAdapter
func (_mock *MockAdapter) FilterRoles(ctx context.Context, data FilterRolesData) ([]FilterRolesResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for FilterRoles")
	}

	var r0 []FilterRolesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterRolesData) ([]FilterRolesResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterRolesData) []FilterRolesResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FilterRolesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FilterRolesData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_FilterRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterRoles'
type MockAdapter_FilterRoles_Call struct {
	*mock.Call
}

// FilterRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - data FilterRolesData
func (_e *MockAdapter_Expecter) FilterRoles(ctx interface{}, data interface{}) *MockAdapter_FilterRoles_Call {
	return &MockAdapter_FilterRoles_Call{Call: _e.mock.On("FilterRoles", ctx, data)}
}

func (_c *MockAdapter_FilterRoles_Call) Run(run func(ctx context.Context, data FilterRolesData)) *MockAdapter_FilterRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FilterRolesData
		if args[1] != nil {
			arg1 = args[1].(FilterRolesData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_FilterRoles_Call) Return(filterRolesResults []FilterRolesResult, err error) *MockAdapter_FilterRoles_Call {
	_c.Call.Return(filterRolesResults, err)
	return _c
}

func (_c *MockAdapter_FilterRoles_Call) RunAndReturn(run func(ctx context.Context, data FilterRolesData) ([]FilterRolesResult, error)) *MockAdapter_FilterRoles_Call {
	_c.Call.Return(run)
	return _c
}

// PeriodicRolesCacheSync provides a mock function for the type MockAdapter
func (_mock *MockAdapter) PeriodicRolesCacheSync(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockAdapter_PeriodicRolesCacheSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeriodicRolesCacheSync'
type MockAdapter_PeriodicRolesCacheSync_Call struct {
	*mock.Call
}

// PeriodicRolesCacheSync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdapter_Expecter) PeriodicRolesCacheSync(ctx interface{}) *MockAdapter_PeriodicRolesCacheSync_Call {
	return &MockAdapter_PeriodicRolesCacheSync_Call{Call: _e.mock.On("PeriodicRolesCacheSync", ctx)}
}

func (_c *MockAdapter_PeriodicRolesCacheSync_Call) Run(run func(ctx context.Context)) *MockAdapter_PeriodicRolesCacheSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdapter_PeriodicRolesCacheSync_Call) Return() *MockAdapter_PeriodicRolesCacheSync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_PeriodicRolesCacheSync_Call) RunAndReturn(run func(ctx context.Context)) *MockAdapter_PeriodicRolesCacheSync_Call {
	_c.Run(run)
	return _c
}

// SubscribeRoleUpdates provides a mock function for the type MockAdapter
func (_mock *MockAdapter) SubscribeRoleUpdates(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockAdapter_SubscribeRoleUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeRoleUpdates'
type MockAdapter_SubscribeRoleUpdates_Call struct {
	*mock.Call
}

// SubscribeRoleUpdates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdapter_Expecter) SubscribeRoleUpdates(ctx interface{}) *MockAdapter_SubscribeRoleUpdates_Call {
	return &MockAdapter_SubscribeRoleUpdates_Call{Call: _e.mock.On("SubscribeRoleUpdates", ctx)}
}

func (_c *MockAdapter_SubscribeRoleUpdates_Call) Run(run func(ctx context.Context)) *MockAdapter_SubscribeRoleUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdapter_SubscribeRoleUpdates_Call) Return() *MockAdapter_SubscribeRoleUpdates_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_SubscribeRoleUpdates_Call) RunAndReturn(run func(ctx context.Context)) *MockAdapter_SubscribeRoleUpdates_Call {
	_c.Run(run)
	return _c
}

// UpdateRole provides a mock function for the type MockAdapter
func (_mock *MockAdapter) UpdateRole(ctx context.Context, id string, data map[string]any) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockAdapter_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data map[string]any
func (_e *MockAdapter_Expecter) UpdateRole(ctx interface{}, id interface{}, data interface{}) *MockAdapter_UpdateRole_Call {
	return &MockAdapter_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, data)}
}

func (_c *MockAdapter_UpdateRole_Call) Run(run func(ctx context.Context, id string, data map[string]any)) *MockAdapter_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_UpdateRole_Call) Return(err error) *MockAdapter_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, id string, data map[string]any) error) *MockAdapter_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRolesCache provides a mock function for the type MockAdapter
func (_mock *MockAdapter) UpdateRolesCache(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRolesCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_UpdateRolesCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRolesCache'
type MockAdapter_UpdateRolesCache_Call struct {
	*mock.Call
}

// UpdateRolesCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdapter_Expecter) UpdateRolesCache(ctx interface{}) *MockAdapter_UpdateRolesCache_Call {
	return &MockAdapter_UpdateRolesCache_Call{Call: _e.mock.On("UpdateRolesCache", ctx)}
}

func (_c *MockAdapter_UpdateRolesCache_Call) Run(run func(ctx context.Context)) *MockAdapter_UpdateRolesCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdapter_UpdateRolesCache_Call) Return(err error) *MockAdapter_UpdateRolesCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_UpdateRolesCache_Call) RunAndReturn(run func(ctx context.Context) error) *MockAdapter_UpdateRolesCache_Call {
	_c.Call.Return(run)
	return _c
}
