// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/transport/http/server"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Logout(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAdapter_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) Logout(ctx interface{}, reqCtx interface{}) *MockAdapter_Logout_Call {
	return &MockAdapter_Logout_Call{Call: _e.mock.On("Logout", ctx, reqCtx)}
}

func (_c *MockAdapter_Logout_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_Logout_Call) Return() *MockAdapter_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_Logout_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_Logout_Call {
	_c.Run(run)
	return _c
}

// LogoutAll provides a mock function for the type MockAdapter
func (_mock *MockAdapter) LogoutAll(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAdapter_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) LogoutAll(ctx interface{}, reqCtx interface{}) *MockAdapter_LogoutAll_Call {
	return &MockAdapter_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, reqCtx)}
}

func (_c *MockAdapter_LogoutAll_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_LogoutAll_Call) Return() *MockAdapter_LogoutAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_LogoutAll_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_LogoutAll_Call {
	_c.Run(run)
	return _c
}

// LogoutDevice provides a mock function for the type MockAdapter
func (_mock *MockAdapter) LogoutDevice(ctx context.Context, reqCtx *server.RequestContext, req *LogoutDeviceRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_LogoutDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutDevice'
type MockAdapter_LogoutDevice_Call struct {
	*mock.Call
}

// LogoutDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *LogoutDeviceRequest
func (_e *MockAdapter_Expecter) LogoutDevice(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_LogoutDevice_Call {
	return &MockAdapter_LogoutDevice_Call{Call: _e.mock.On("LogoutDevice", ctx, reqCtx, req)}
}

func (_c *MockAdapter_LogoutDevice_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *LogoutDeviceRequest)) *MockAdapter_LogoutDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *LogoutDeviceRequest
		if args[2] != nil {
			arg2 = args[2].(*LogoutDeviceRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_LogoutDevice_Call) Return() *MockAdapter_LogoutDevice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_LogoutDevice_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *LogoutDeviceRequest)) *MockAdapter_LogoutDevice_Call {
	_c.Run(run)
	return _c
}
