// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package postgres

import (
	"fmt"
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/db/postgres"
	"go.microcore.dev/framework/db/postgres/client"
	"go.microcore.dev/framework/shutdown"
)

// Injectors from wire.go:

func Init(opts *Options) (*Postgres, error) {
	config := NewConfig()
	manager, err := newManager(config)
	if err != nil {
		return nil, err
	}
	postgres := newPostgres(config, opts, manager)
	return postgres, nil
}

// wire.go:

type (
	Options struct {
		Telemetry *telemetry.Telemetry
	}
)

func newManager(
	config *Config,
) (postgres.Manager, error) {
	manager, err := postgres.New(postgres.WithClientOptions(client.WithPostgresDSN(fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",
		config.Host,
		config.Port,
		config.User,
		config.Password,
		config.DB,
		config.SSL,
	),
	),
	),
	)
	if err != nil {
		return nil, shutdown.NewExitReason(shutdown.ExitUnavailable, fmt.Errorf("create postgres manager: %w", err))
	}
	return manager, nil
}

func newPostgres(
	config *Config,
	opts *Options,
	manager postgres.Manager,
) *Postgres {
	return &Postgres{
		Config:    config,
		Telemetry: opts.Telemetry,
		Manager:   manager,
	}
}
