// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package redis

import (
	"go.microcore.dev/auth-service/internal/shared/telemetry"
	"go.microcore.dev/framework/db/redis"
	"go.microcore.dev/framework/db/redis/client"
)

// Injectors from wire.go:

func Init(opts *Options) (*Redis, error) {
	config := NewConfig()
	manager := newManager(config)
	redis := newRedis(config, opts, manager)
	return redis, nil
}

// wire.go:

type (
	Options struct {
		Telemetry *telemetry.Telemetry
	}
)

func newManager(
	config *Config,
) redis.Manager {
	return redis.New(redis.WithClientOptions(client.WithAddr(config.Addr), client.WithPassword(config.Password), client.WithDB(config.DB)),
	)
}

func newRedis(
	config *Config,
	opts *Options,
	manager redis.Manager,
) *Redis {
	return &Redis{
		Config:    config,
		Telemetry: opts.Telemetry,
		Manager:   manager,
	}
}
