// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rules

import (
	"go.microcore.dev/auth-service/internal/port/adapter/repository/rules"
	"go.microcore.dev/auth-service/internal/shared/postgres"
	"go.microcore.dev/auth-service/internal/shared/redis"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (rules.Adapter, error) {
	logger := newLogger()
	rulesAdapter := newAdapter(opts, logger)
	return rulesAdapter, nil
}

// wire.go:

type (
	Options struct {
		Postgres *postgres.Postgres
		Redis    *redis.Redis
	}
)

func newLogger() *slog.Logger {
	return log.New("repository/rules")
}

func newAdapter(
	opts *Options,
	logger *slog.Logger,
) rules.Adapter {
	return NewAdapter(
		&AdapterConfig{
			Logger:   logger,
			Redis:    opts.Redis,
			Postgres: opts.Postgres,
		},
	)
}
