// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/transport/http/server"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// ListDevices provides a mock function for the type MockAdapter
func (_mock *MockAdapter) ListDevices(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type MockAdapter_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) ListDevices(ctx interface{}, reqCtx interface{}) *MockAdapter_ListDevices_Call {
	return &MockAdapter_ListDevices_Call{Call: _e.mock.On("ListDevices", ctx, reqCtx)}
}

func (_c *MockAdapter_ListDevices_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_ListDevices_Call) Return() *MockAdapter_ListDevices_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_ListDevices_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_ListDevices_Call {
	_c.Run(run)
	return _c
}
