// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rules

import (
	rules2 "go.microcore.dev/auth-service/internal/port/adapter/repository/rules"
	"go.microcore.dev/auth-service/internal/port/service/rules"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (rules.Service, error) {
	logger := newLogger()
	rulesService := newService(opts, logger)
	return rulesService, nil
}

// wire.go:

type (
	Options struct {
		RulesRepository rules2.Adapter
	}
)

func newLogger() *slog.Logger {
	return log.New("service/rules")
}

func newService(
	opts *Options,
	logger *slog.Logger,
) rules.Service {
	return NewService(
		&ServiceConfig{
			Logger:          logger,
			RulesRepository: opts.RulesRepository,
		},
	)
}
