// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package roles

import (
	"go.microcore.dev/auth-service/internal/port/adapter/repository/roles"
	"go.microcore.dev/auth-service/internal/shared/postgres"
	"go.microcore.dev/auth-service/internal/shared/redis"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (roles.Adapter, error) {
	config := NewConfig()
	logger := newLogger()
	rolesAdapter := newAdapter(config, opts, logger)
	return rolesAdapter, nil
}

// wire.go:

type (
	Options struct {
		Postgres *postgres.Postgres
		Redis    *redis.Redis
	}
)

func newLogger() *slog.Logger {
	return log.New("repository/roles")
}

func newAdapter(
	config *Config,
	opts *Options,
	logger *slog.Logger,
) roles.Adapter {
	return NewAdapter(
		&AdapterConfig{
			Config:   config,
			Logger:   logger,
			Redis:    opts.Redis,
			Postgres: opts.Postgres,
		},
	)
}
