// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/devices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Returns a list of user's active devices.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.DeviceResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logout"
                ],
                "summary": "Terminate the current session on user device.",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout/all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logout"
                ],
                "summary": "Terminate all active sessions for a user across all devices.",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout/device": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logout"
                ],
                "summary": "Terminate the session on a selected user device.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.LogoutDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Possible codes: INVALID_DEVICE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/roles/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Creates a new role.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.CreateRoleResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ROLE_ID, INVALID_ROLE_NAME, INVALID_ROLE_DESCRIPTION, ROLE_EXIST_ID",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/roles/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Returns roles matching the filter criteria.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.FilterRolesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.FilterRolesResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/roles/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Deletes a role by ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ROLE_ID",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Possible codes: ROLE_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Updates role data by ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http._UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ROLE_ID, INVALID_ROLE_NAME, INVALID_ROLE_DESCRIPTION",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Possible codes: ROLE_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/rules/http/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rules (HTTP)"
                ],
                "summary": "Creates a new HTTP rule.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateHTTPRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.CreateHTTPRuleResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ROLE_ID, INVALID_PATH, INVALID_METHODS, RULE_EXIST",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/rules/http/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rules (HTTP)"
                ],
                "summary": "Returns HTTP rules matching the filter criteria.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.FilterHTTPRulesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.FilterHTTPRulesResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/rules/http/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rules (HTTP)"
                ],
                "summary": "Deletes an HTTP rule by ID.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ID",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Possible codes: RULE_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rules (HTTP)"
                ],
                "summary": "Updates an HTTP rule by ID.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http._UpdateHTTPRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ID, INVALID_ROLE_ID, INVALID_PATH, INVALID_METHODS, INVALID_MFA",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Possible codes: RULE_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream",
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "Issues JWT tokens.",
                "parameters": [
                    {
                        "description": "BINARY DATA REQUIRED: Encrypt this JSON structure using AES-256-GCM with AUTH_KEY before sending",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns encrypted binary. Decrypt using AES-256-GCM with AUTH_KEY to get this JSON structure.",
                        "schema": {
                            "$ref": "#/definitions/http.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_AUTH_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/2fa": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream",
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "Issues JWT tokens after successful 2FA.",
                "parameters": [
                    {
                        "description": "BINARY DATA REQUIRED: Encrypt this JSON structure using AES-256-GCM with AUTH_KEY before sending",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.Auth2FARequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns encrypted binary. Decrypt using AES-256-GCM with AUTH_KEY to get this JSON structure.",
                        "schema": {
                            "$ref": "#/definitions/http.Auth2FAResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_AUTH_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/authorize/http": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Parsing, validation and authorize of the access token. Mainly used in the authorization mechanism across various microservices.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "Checks HTTP authorization for given access token.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.TokenAuthorizeHTTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.TokenAuthorizeHTTPResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_PATH, INVALID_METHOD",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/renew": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "Renews JWT tokens based on a refresh token.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.TokenRenewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.TokenRenewResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_TOKEN, TOKEN_ALREADY_USED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/static/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Static tokens"
                ],
                "summary": "Creates a static access token.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateStaticAccessTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.CreateStaticAccessTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ID, INVALID_ROLES, INVALID_DESCRIPTION, STATIC_TOKEN_EXIST",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/static/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Static tokens"
                ],
                "summary": "Filters static access tokens.",
                "parameters": [
                    {
                        "description": "Request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.FilterStaticAccessTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.FilterStaticAccessTokenResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "415": {
                        "description": "Possible codes: INVALID_JSON_BODY",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/static/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Static tokens"
                ],
                "summary": "Deletes a static access token by ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Possible codes: INVALID_ID",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Possible codes: INVALID_ID, STATIC_TOKEN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/tokens/validate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Parsing and validation of the access token. Mainly used in the authorization mechanism across various microservices.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "Validates an access token.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.TokenValidateResponse"
                        }
                    },
                    "401": {
                        "description": "Possible codes: INVALID_TOKEN, 2FA_REQUIRED",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Possible codes: INSUFFICIENT_PERMISSIONS",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Possible codes: SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/server.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.Auth2FARequest": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ttl": {
                    "type": "string"
                },
                "user": {
                    "type": "integer"
                }
            }
        },
        "http.Auth2FAResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                },
                "refresh": {
                    "type": "string"
                }
            }
        },
        "http.AuthRequest": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "metaBrowserName": {
                    "type": "string"
                },
                "metaBrowserVersion": {
                    "type": "string"
                },
                "metaEngineName": {
                    "type": "string"
                },
                "metaEngineVersion": {
                    "type": "string"
                },
                "metaIp": {
                    "type": "string"
                },
                "metaLocation": {
                    "type": "string"
                },
                "metaModel": {
                    "type": "string"
                },
                "metaOsFullName": {
                    "type": "string"
                },
                "metaOsName": {
                    "type": "string"
                },
                "metaOsVersion": {
                    "type": "string"
                },
                "metaPlatform": {
                    "type": "string"
                },
                "metaUserAgent": {
                    "type": "string"
                },
                "mfa": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ttl": {
                    "type": "string"
                },
                "user": {
                    "type": "integer"
                }
            }
        },
        "http.AuthResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                },
                "mfa": {
                    "type": "boolean"
                },
                "newDevice": {
                    "type": "boolean"
                },
                "refresh": {
                    "type": "string"
                }
            }
        },
        "http.CreateHTTPRuleRequest": {
            "type": "object",
            "properties": {
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mfa": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                }
            }
        },
        "http.CreateHTTPRuleResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mfa": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "http.CreateRoleRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "serviceFlag": {
                    "type": "boolean"
                },
                "systemFlag": {
                    "type": "boolean"
                }
            }
        },
        "http.CreateRoleResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "serviceFlag": {
                    "type": "boolean"
                },
                "systemFlag": {
                    "type": "boolean"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "http.CreateStaticAccessTokenRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.CreateStaticAccessTokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "http.DeviceResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "session": {
                    "$ref": "#/definitions/http.SessionResponse"
                }
            }
        },
        "http.FilterHTTPRulesRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mfa": {
                    "type": "boolean"
                },
                "path": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roleId": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.FilterHTTPRulesResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mfa": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "http.FilterRolesRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "serviceFlag": {
                    "type": "boolean"
                },
                "systemFlag": {
                    "type": "boolean"
                }
            }
        },
        "http.FilterRolesResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "httpRules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.HTTPRuleResponse"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "serviceFlag": {
                    "type": "boolean"
                },
                "systemFlag": {
                    "type": "boolean"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "http.FilterStaticAccessTokenRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.FilterStaticAccessTokenResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "http.HTTPRuleResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mfa": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "http.LogoutDeviceRequest": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                }
            }
        },
        "http.SessionResponse": {
            "type": "object",
            "properties": {
                "browserName": {
                    "type": "string"
                },
                "browserVersion": {
                    "type": "string"
                },
                "engineName": {
                    "type": "string"
                },
                "engineVersion": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "issuedAt": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "osFullName": {
                    "type": "string"
                },
                "osName": {
                    "type": "string"
                },
                "osVersion": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "userAgent": {
                    "type": "string"
                }
            }
        },
        "http.TokenAuthorizeHTTPAuthResponse": {
            "type": "object",
            "properties": {
                "mfa": {
                    "type": "boolean"
                }
            }
        },
        "http.TokenAuthorizeHTTPDataResponse": {
            "type": "object",
            "properties": {
                "audience": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "device": {
                    "type": "string"
                },
                "expires": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "issued": {
                    "type": "integer"
                },
                "issuer": {
                    "type": "string"
                },
                "mfa": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user": {
                    "type": "integer"
                }
            }
        },
        "http.TokenAuthorizeHTTPRequest": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "http.TokenAuthorizeHTTPResponse": {
            "type": "object",
            "properties": {
                "auth": {
                    "$ref": "#/definitions/http.TokenAuthorizeHTTPAuthResponse"
                },
                "token": {
                    "$ref": "#/definitions/http.TokenAuthorizeHTTPDataResponse"
                }
            }
        },
        "http.TokenRenewRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "http.TokenRenewResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "mfaRequired": {
                    "type": "boolean"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "http.TokenValidateResponse": {
            "type": "object",
            "properties": {
                "audience": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "device": {
                    "type": "string"
                },
                "expires": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "issued": {
                    "type": "integer"
                },
                "issuer": {
                    "type": "string"
                },
                "mfa": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user": {
                    "type": "integer"
                }
            }
        },
        "http._UpdateHTTPRuleRequest": {
            "type": "object",
            "properties": {
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mfa": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                }
            }
        },
        "http._UpdateRoleRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "server.ErrResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "auth-service",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
