// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rules

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateHTTPRule provides a mock function for the type MockService
func (_mock *MockService) CreateHTTPRule(ctx context.Context, data CreateHTTPRuleData) (*CreateHTTPRuleResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateHTTPRule")
	}

	var r0 *CreateHTTPRuleResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateHTTPRuleData) (*CreateHTTPRuleResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateHTTPRuleData) *CreateHTTPRuleResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateHTTPRuleResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateHTTPRuleData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateHTTPRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHTTPRule'
type MockService_CreateHTTPRule_Call struct {
	*mock.Call
}

// CreateHTTPRule is a helper method to define mock.On call
//   - ctx context.Context
//   - data CreateHTTPRuleData
func (_e *MockService_Expecter) CreateHTTPRule(ctx interface{}, data interface{}) *MockService_CreateHTTPRule_Call {
	return &MockService_CreateHTTPRule_Call{Call: _e.mock.On("CreateHTTPRule", ctx, data)}
}

func (_c *MockService_CreateHTTPRule_Call) Run(run func(ctx context.Context, data CreateHTTPRuleData)) *MockService_CreateHTTPRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateHTTPRuleData
		if args[1] != nil {
			arg1 = args[1].(CreateHTTPRuleData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateHTTPRule_Call) Return(createHTTPRuleResult *CreateHTTPRuleResult, err error) *MockService_CreateHTTPRule_Call {
	_c.Call.Return(createHTTPRuleResult, err)
	return _c
}

func (_c *MockService_CreateHTTPRule_Call) RunAndReturn(run func(ctx context.Context, data CreateHTTPRuleData) (*CreateHTTPRuleResult, error)) *MockService_CreateHTTPRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHTTPRule provides a mock function for the type MockService
func (_mock *MockService) DeleteHTTPRule(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHTTPRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteHTTPRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHTTPRule'
type MockService_DeleteHTTPRule_Call struct {
	*mock.Call
}

// DeleteHTTPRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockService_Expecter) DeleteHTTPRule(ctx interface{}, id interface{}) *MockService_DeleteHTTPRule_Call {
	return &MockService_DeleteHTTPRule_Call{Call: _e.mock.On("DeleteHTTPRule", ctx, id)}
}

func (_c *MockService_DeleteHTTPRule_Call) Run(run func(ctx context.Context, id uint)) *MockService_DeleteHTTPRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteHTTPRule_Call) Return(err error) *MockService_DeleteHTTPRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteHTTPRule_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockService_DeleteHTTPRule_Call {
	_c.Call.Return(run)
	return _c
}

// FilterHTTPRules provides a mock function for the type MockService
func (_mock *MockService) FilterHTTPRules(ctx context.Context, data FilterHTTPRulesData) ([]FilterHTTPRulesResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for FilterHTTPRules")
	}

	var r0 []FilterHTTPRulesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterHTTPRulesData) ([]FilterHTTPRulesResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterHTTPRulesData) []FilterHTTPRulesResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FilterHTTPRulesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FilterHTTPRulesData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FilterHTTPRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterHTTPRules'
type MockService_FilterHTTPRules_Call struct {
	*mock.Call
}

// FilterHTTPRules is a helper method to define mock.On call
//   - ctx context.Context
//   - data FilterHTTPRulesData
func (_e *MockService_Expecter) FilterHTTPRules(ctx interface{}, data interface{}) *MockService_FilterHTTPRules_Call {
	return &MockService_FilterHTTPRules_Call{Call: _e.mock.On("FilterHTTPRules", ctx, data)}
}

func (_c *MockService_FilterHTTPRules_Call) Run(run func(ctx context.Context, data FilterHTTPRulesData)) *MockService_FilterHTTPRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FilterHTTPRulesData
		if args[1] != nil {
			arg1 = args[1].(FilterHTTPRulesData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FilterHTTPRules_Call) Return(filterHTTPRulesResults []FilterHTTPRulesResult, err error) *MockService_FilterHTTPRules_Call {
	_c.Call.Return(filterHTTPRulesResults, err)
	return _c
}

func (_c *MockService_FilterHTTPRules_Call) RunAndReturn(run func(ctx context.Context, data FilterHTTPRulesData) ([]FilterHTTPRulesResult, error)) *MockService_FilterHTTPRules_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHTTPRule provides a mock function for the type MockService
func (_mock *MockService) UpdateHTTPRule(ctx context.Context, id uint, data map[string]any) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHTTPRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, map[string]any) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateHTTPRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHTTPRule'
type MockService_UpdateHTTPRule_Call struct {
	*mock.Call
}

// UpdateHTTPRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - data map[string]any
func (_e *MockService_Expecter) UpdateHTTPRule(ctx interface{}, id interface{}, data interface{}) *MockService_UpdateHTTPRule_Call {
	return &MockService_UpdateHTTPRule_Call{Call: _e.mock.On("UpdateHTTPRule", ctx, id, data)}
}

func (_c *MockService_UpdateHTTPRule_Call) Run(run func(ctx context.Context, id uint, data map[string]any)) *MockService_UpdateHTTPRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateHTTPRule_Call) Return(err error) *MockService_UpdateHTTPRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateHTTPRule_Call) RunAndReturn(run func(ctx context.Context, id uint, data map[string]any) error) *MockService_UpdateHTTPRule_Call {
	_c.Call.Return(run)
	return _c
}
