// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package devices

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetActiveDevices provides a mock function for the type MockService
func (_mock *MockService) GetActiveDevices(ctx context.Context, user uint) ([]DeviceResult, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveDevices")
	}

	var r0 []DeviceResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]DeviceResult, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []DeviceResult); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DeviceResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetActiveDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveDevices'
type MockService_GetActiveDevices_Call struct {
	*mock.Call
}

// GetActiveDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - user uint
func (_e *MockService_Expecter) GetActiveDevices(ctx interface{}, user interface{}) *MockService_GetActiveDevices_Call {
	return &MockService_GetActiveDevices_Call{Call: _e.mock.On("GetActiveDevices", ctx, user)}
}

func (_c *MockService_GetActiveDevices_Call) Run(run func(ctx context.Context, user uint)) *MockService_GetActiveDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetActiveDevices_Call) Return(deviceResults []DeviceResult, err error) *MockService_GetActiveDevices_Call {
	_c.Call.Return(deviceResults, err)
	return _c
}

func (_c *MockService_GetActiveDevices_Call) RunAndReturn(run func(ctx context.Context, user uint) ([]DeviceResult, error)) *MockService_GetActiveDevices_Call {
	_c.Call.Return(run)
	return _c
}
