// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package roles

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AuthorizeHTTPRoles provides a mock function for the type MockService
func (_mock *MockService) AuthorizeHTTPRoles(ctx context.Context, data AuthorizeHTTPRolesData) (*AuthorizeHTTPRolesResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeHTTPRoles")
	}

	var r0 *AuthorizeHTTPRolesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuthorizeHTTPRolesData) (*AuthorizeHTTPRolesResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuthorizeHTTPRolesData) *AuthorizeHTTPRolesResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthorizeHTTPRolesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AuthorizeHTTPRolesData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AuthorizeHTTPRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeHTTPRoles'
type MockService_AuthorizeHTTPRoles_Call struct {
	*mock.Call
}

// AuthorizeHTTPRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - data AuthorizeHTTPRolesData
func (_e *MockService_Expecter) AuthorizeHTTPRoles(ctx interface{}, data interface{}) *MockService_AuthorizeHTTPRoles_Call {
	return &MockService_AuthorizeHTTPRoles_Call{Call: _e.mock.On("AuthorizeHTTPRoles", ctx, data)}
}

func (_c *MockService_AuthorizeHTTPRoles_Call) Run(run func(ctx context.Context, data AuthorizeHTTPRolesData)) *MockService_AuthorizeHTTPRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AuthorizeHTTPRolesData
		if args[1] != nil {
			arg1 = args[1].(AuthorizeHTTPRolesData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AuthorizeHTTPRoles_Call) Return(authorizeHTTPRolesResult *AuthorizeHTTPRolesResult, err error) *MockService_AuthorizeHTTPRoles_Call {
	_c.Call.Return(authorizeHTTPRolesResult, err)
	return _c
}

func (_c *MockService_AuthorizeHTTPRoles_Call) RunAndReturn(run func(ctx context.Context, data AuthorizeHTTPRolesData) (*AuthorizeHTTPRolesResult, error)) *MockService_AuthorizeHTTPRoles_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type MockService
func (_mock *MockService) CreateRole(ctx context.Context, data CreateRoleData) (*CreateRoleResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *CreateRoleResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRoleData) (*CreateRoleResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateRoleData) *CreateRoleResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateRoleResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateRoleData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - data CreateRoleData
func (_e *MockService_Expecter) CreateRole(ctx interface{}, data interface{}) *MockService_CreateRole_Call {
	return &MockService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, data)}
}

func (_c *MockService_CreateRole_Call) Run(run func(ctx context.Context, data CreateRoleData)) *MockService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateRoleData
		if args[1] != nil {
			arg1 = args[1].(CreateRoleData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateRole_Call) Return(createRoleResult *CreateRoleResult, err error) *MockService_CreateRole_Call {
	_c.Call.Return(createRoleResult, err)
	return _c
}

func (_c *MockService_CreateRole_Call) RunAndReturn(run func(ctx context.Context, data CreateRoleData) (*CreateRoleResult, error)) *MockService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockService
func (_mock *MockService) DeleteRole(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockService_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteRole(ctx interface{}, id interface{}) *MockService_DeleteRole_Call {
	return &MockService_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, id)}
}

func (_c *MockService_DeleteRole_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteRole_Call) Return(err error) *MockService_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// FilterRoles provides a mock function for the type MockService
func (_mock *MockService) FilterRoles(ctx context.Context, data FilterRolesData) ([]FilterRolesResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for FilterRoles")
	}

	var r0 []FilterRolesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterRolesData) ([]FilterRolesResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FilterRolesData) []FilterRolesResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FilterRolesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FilterRolesData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FilterRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterRoles'
type MockService_FilterRoles_Call struct {
	*mock.Call
}

// FilterRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - data FilterRolesData
func (_e *MockService_Expecter) FilterRoles(ctx interface{}, data interface{}) *MockService_FilterRoles_Call {
	return &MockService_FilterRoles_Call{Call: _e.mock.On("FilterRoles", ctx, data)}
}

func (_c *MockService_FilterRoles_Call) Run(run func(ctx context.Context, data FilterRolesData)) *MockService_FilterRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FilterRolesData
		if args[1] != nil {
			arg1 = args[1].(FilterRolesData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FilterRoles_Call) Return(filterRolesResults []FilterRolesResult, err error) *MockService_FilterRoles_Call {
	_c.Call.Return(filterRolesResults, err)
	return _c
}

func (_c *MockService_FilterRoles_Call) RunAndReturn(run func(ctx context.Context, data FilterRolesData) ([]FilterRolesResult, error)) *MockService_FilterRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockService
func (_mock *MockService) UpdateRole(ctx context.Context, id string, data map[string]any) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockService_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data map[string]any
func (_e *MockService_Expecter) UpdateRole(ctx interface{}, id interface{}, data interface{}) *MockService_UpdateRole_Call {
	return &MockService_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, data)}
}

func (_c *MockService_UpdateRole_Call) Run(run func(ctx context.Context, id string, data map[string]any)) *MockService_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateRole_Call) Return(err error) *MockService_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, id string, data map[string]any) error) *MockService_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
