// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/transport/http/server"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// CreateRole provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CreateRole(ctx context.Context, reqCtx *server.RequestContext, req *CreateRoleRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockAdapter_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *CreateRoleRequest
func (_e *MockAdapter_Expecter) CreateRole(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_CreateRole_Call {
	return &MockAdapter_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, reqCtx, req)}
}

func (_c *MockAdapter_CreateRole_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *CreateRoleRequest)) *MockAdapter_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *CreateRoleRequest
		if args[2] != nil {
			arg2 = args[2].(*CreateRoleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_CreateRole_Call) Return() *MockAdapter_CreateRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_CreateRole_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *CreateRoleRequest)) *MockAdapter_CreateRole_Call {
	_c.Run(run)
	return _c
}

// DeleteRole provides a mock function for the type MockAdapter
func (_mock *MockAdapter) DeleteRole(ctx context.Context, reqCtx *server.RequestContext) {
	_mock.Called(ctx, reqCtx)
	return
}

// MockAdapter_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockAdapter_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
func (_e *MockAdapter_Expecter) DeleteRole(ctx interface{}, reqCtx interface{}) *MockAdapter_DeleteRole_Call {
	return &MockAdapter_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, reqCtx)}
}

func (_c *MockAdapter_DeleteRole_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_DeleteRole_Call) Return() *MockAdapter_DeleteRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext)) *MockAdapter_DeleteRole_Call {
	_c.Run(run)
	return _c
}

// FilterRoles provides a mock function for the type MockAdapter
func (_mock *MockAdapter) FilterRoles(ctx context.Context, reqCtx *server.RequestContext, req *FilterRolesRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_FilterRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterRoles'
type MockAdapter_FilterRoles_Call struct {
	*mock.Call
}

// FilterRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *FilterRolesRequest
func (_e *MockAdapter_Expecter) FilterRoles(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_FilterRoles_Call {
	return &MockAdapter_FilterRoles_Call{Call: _e.mock.On("FilterRoles", ctx, reqCtx, req)}
}

func (_c *MockAdapter_FilterRoles_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *FilterRolesRequest)) *MockAdapter_FilterRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *FilterRolesRequest
		if args[2] != nil {
			arg2 = args[2].(*FilterRolesRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_FilterRoles_Call) Return() *MockAdapter_FilterRoles_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_FilterRoles_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *FilterRolesRequest)) *MockAdapter_FilterRoles_Call {
	_c.Run(run)
	return _c
}

// UpdateRole provides a mock function for the type MockAdapter
func (_mock *MockAdapter) UpdateRole(ctx context.Context, reqCtx *server.RequestContext, req *UpdateRoleRequest) {
	_mock.Called(ctx, reqCtx, req)
	return
}

// MockAdapter_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockAdapter_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - reqCtx *server.RequestContext
//   - req *UpdateRoleRequest
func (_e *MockAdapter_Expecter) UpdateRole(ctx interface{}, reqCtx interface{}, req interface{}) *MockAdapter_UpdateRole_Call {
	return &MockAdapter_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, reqCtx, req)}
}

func (_c *MockAdapter_UpdateRole_Call) Run(run func(ctx context.Context, reqCtx *server.RequestContext, req *UpdateRoleRequest)) *MockAdapter_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *server.RequestContext
		if args[1] != nil {
			arg1 = args[1].(*server.RequestContext)
		}
		var arg2 *UpdateRoleRequest
		if args[2] != nil {
			arg2 = args[2].(*UpdateRoleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_UpdateRole_Call) Return() *MockAdapter_UpdateRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdapter_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, reqCtx *server.RequestContext, req *UpdateRoleRequest)) *MockAdapter_UpdateRole_Call {
	_c.Run(run)
	return _c
}
