// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/transport/http/server"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// AuthMiddleware provides a mock function for the type MockAdapter
func (_mock *MockAdapter) AuthMiddleware(handler server.RequestHandler) server.RequestHandler {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for AuthMiddleware")
	}

	var r0 server.RequestHandler
	if returnFunc, ok := ret.Get(0).(func(server.RequestHandler) server.RequestHandler); ok {
		r0 = returnFunc(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(server.RequestHandler)
		}
	}
	return r0
}

// MockAdapter_AuthMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthMiddleware'
type MockAdapter_AuthMiddleware_Call struct {
	*mock.Call
}

// AuthMiddleware is a helper method to define mock.On call
//   - handler server.RequestHandler
func (_e *MockAdapter_Expecter) AuthMiddleware(handler interface{}) *MockAdapter_AuthMiddleware_Call {
	return &MockAdapter_AuthMiddleware_Call{Call: _e.mock.On("AuthMiddleware", handler)}
}

func (_c *MockAdapter_AuthMiddleware_Call) Run(run func(handler server.RequestHandler)) *MockAdapter_AuthMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 server.RequestHandler
		if args[0] != nil {
			arg0 = args[0].(server.RequestHandler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdapter_AuthMiddleware_Call) Return(requestHandler server.RequestHandler) *MockAdapter_AuthMiddleware_Call {
	_c.Call.Return(requestHandler)
	return _c
}

func (_c *MockAdapter_AuthMiddleware_Call) RunAndReturn(run func(handler server.RequestHandler) server.RequestHandler) *MockAdapter_AuthMiddleware_Call {
	_c.Call.Return(run)
	return _c
}
