// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tokens

import (
	"go.microcore.dev/auth-service/internal/port/adapter/repository/auth"
	"go.microcore.dev/auth-service/internal/port/service/tokens"
	"go.microcore.dev/framework/log"
	"log/slog"
)

// Injectors from wire.go:

func Init(opts *Options) (tokens.Service, error) {
	config := NewConfig()
	logger := newLogger()
	tokensService := newService(opts, config, logger)
	return tokensService, nil
}

// wire.go:

type (
	Options struct {
		AuthRepository auth.Adapter
	}
)

func newLogger() *slog.Logger {
	return log.New("service/tokens")
}

func newService(
	opts *Options,
	config *Config,
	logger *slog.Logger,
) tokens.Service {
	return NewService(
		&ServiceConfig{
			Config:         config,
			Logger:         logger,
			AuthRepository: opts.AuthRepository,
		},
	)
}
